// Zone 3, Thornpeak Heights (levels 13-20). The Gravecallers serve Korzul
// the Gravewyrm, an ancient dragon sealed beneath the peaks. Highwatch holds
// the wall against ogres, waking elementals, and the open chanting of the
// Wyrmcult at the Gravewyrm Sanctum gates.

import { WORK_ORDER_CADENCE_TICKS } from '../../professions/cadence';
import type {
  CampDef,
  GroundObjectDef,
  ItemDef,
  MobTemplate,
  NpcDef,
  QuestDef,
  ZoneDef,
  ZonePropsDef,
} from '../../types';
import { FERAL } from '../items';

export const ZONE3_ITEMS: Record<string, ItemDef> = {
  // --- quest items ---
  highwatch_summons: {
    id: 'highwatch_summons',
    name: 'Highwatch Summons',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_highwatch_summons',
  },
  ridge_stalker_pelt: {
    id: 'ridge_stalker_pelt',
    name: 'Ridge Stalker Pelt',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_stalker_pelts',
  },
  glowing_wax: {
    id: 'glowing_wax',
    name: 'Glowing Wax',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_glowing_wax',
  },
  ogre_war_totem: {
    id: 'ogre_war_totem',
    name: 'Ogre War Totem',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_ogre_totems',
  },
  storm_core: {
    id: 'storm_core',
    name: 'Storm Core',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_shard_cores',
  },
  kazzix_heartshard: {
    id: 'kazzix_heartshard',
    name: "Kazzix's Heartshard",
    kind: 'quest',
    sellValue: 0,
    questId: 'q_kazzix',
  },
  wyrmcult_orders: {
    id: 'wyrmcult_orders',
    name: 'Wyrmcult Orders',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_cult_orders',
  },
  ritual_phylactery: {
    id: 'ritual_phylactery',
    name: 'Ritual Phylactery',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_necromancers',
  },
  gravewyrm_sigil: {
    id: 'gravewyrm_sigil',
    name: 'Gravewyrm Sigil',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_wyrm_sigils',
  },
  blessed_embers: {
    id: 'blessed_embers',
    name: 'Blessed Embers',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_breaking_the_seal',
  },
  sanctum_key_shard: {
    id: 'sanctum_key_shard',
    name: 'Sanctum Key Shard',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sanctum_gate',
  },
  runed_bone_shard: {
    id: 'runed_bone_shard',
    name: 'Runed Bone Shard',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_nythraxis_restless_dead',
  },
  grave_sir_aldren: {
    id: 'grave_sir_aldren',
    name: 'Grave of Captain Aldren',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_nythraxis_graves',
  },
  grave_high_priest_malric: {
    id: 'grave_high_priest_malric',
    name: 'Grave of High Priest Malric',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_nythraxis_graves',
  },
  grave_captain_voss: {
    id: 'grave_captain_voss',
    name: 'Grave of Royal Assassin Voss',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_nythraxis_graves',
  },
  ancient_crypt_door: {
    id: 'ancient_crypt_door',
    name: 'Ancient Crypt Door',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_nythraxis_sealed_crypt',
  },
  captains_crest: {
    id: 'captains_crest',
    name: 'Crypt Keystone Upper',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_nythraxis_sealed_crypt',
  },
  priests_sigil: {
    id: 'priests_sigil',
    name: 'Crypt Keystone Lower',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_nythraxis_sealed_crypt',
  },
  royal_seal: {
    id: 'royal_seal',
    name: 'Ancient Diary',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_nythraxis_sealed_crypt',
  },
  crypt_keystone: {
    id: 'crypt_keystone',
    name: 'Crypt Keystone',
    kind: 'quest',
    quality: 'uncommon',
    sellValue: 0,
    questId: 'q_nythraxis_bound_guardian',
  },
  crypt_ritual_circle: {
    id: 'crypt_ritual_circle',
    name: 'Ritual Circle',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_nythraxis_bound_guardian',
  },
  kings_signet: {
    id: 'kings_signet',
    name: "King's Signet",
    kind: 'quest',
    quality: 'rare',
    sellValue: 0,
    questId: 'q_nythraxis_bound_guardian',
  },
  // --- quest greens (uncommon) ---
  ridgestalker_treads: {
    id: 'ridgestalker_treads',
    name: 'Ridgestalker Treads',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 1 },
    sellValue: 600,
  },
  // --- Old Cragmaw drops ---
  // Old Cragmaw's signature trophy, guaranteed to the slayer of the rare elite.
  // Pure vendor value, no quest tie, so it always feels like a boss-kill reward
  // and never blocks a turn-in.
  old_cragmaws_pelt: {
    id: 'old_cragmaws_pelt',
    name: "Old Cragmaw's Pelt",
    kind: 'junk',
    quality: 'common',
    sellValue: 300,
  },
  // Old Cragmaw's rare drop, a notch above the Ridgestalker Treads. Leather,
  // so it stays unrestricted by class.
  cragmaw_prowlboots: {
    id: 'cragmaw_prowlboots',
    name: 'Cragmaw Prowlboots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 3 },
    sellValue: 750,
  },
  // A waist piece to pair with the Prowlboots: agi-leaning leather, waist armor
  // sits a touch under the feet slot. Drops less often than the boots.
  cragmaw_huntcord: {
    id: 'cragmaw_huntcord',
    name: "Cragmaw's Huntcord",
    kind: 'armor',
    slot: 'ring',
    quality: 'rare',
    cardSlots: 1,
    stats: { agi: 2, vit: 2 },
    sellValue: 340,
  },
  // --- Level-20 endgame loot: Korzul (5-player Gravewyrm Sanctum) and Nythraxis
  // (10-player raid). Every piece below is NORMALIZED to the stat budget its item
  // level earns (see src/sim/item_level.ts): item level = level 20 + quality bonus,
  // plus a raid bonus for Nythraxis drops, so the raid set reads a tier above the
  // dungeon set. Within each (item level, quality, slot) group the primary-stat sum
  // is identical while each piece keeps its own stat identity (plate str/sta, cloth
  // int/spi, leather agi/sta). tests/item_level.test.ts pins data == formula. ---
  boneplate_vest: {
    id: 'boneplate_vest',
    name: 'Boneplate Vest',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 2 },
    sellValue: 800,
    requiredClass: ['swordman'],
  },
  revenant_silk_robe: {
    id: 'revenant_silk_robe',
    name: 'Revenant Silk Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 1 },
    sellValue: 800,
    requiredClass: ['mage', 'acolyte'],
  },
  nightwalk_jerkin: {
    id: 'nightwalk_jerkin',
    name: 'Nightwalk Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 2 },
    sellValue: 800,
    requiredClass: ['thief', 'archer'],
  },
  zealotsbane_blade: {
    id: 'zealotsbane_blade',
    name: 'Zealotsbane Blade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 71, max: 94, speed: 2.3, weaponType: 'sword', weaponLevel: 2 },
    stats: { str: 6, vit: 2 },
    sellValue: 900,
    requiredClass: ['swordman', 'thief', 'archer'],
  },
  emberwood_staff: {
    id: 'emberwood_staff',
    name: 'Emberwood Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 39, max: 52, speed: 3.0, weaponType: 'rod', weaponLevel: 2 },
    stats: { int: 6, luk: 2 },
    sellValue: 900,
    requiredClass: ['mage', 'acolyte'],
  },
  cultist_flayer: {
    id: 'cultist_flayer',
    name: 'Cultist Flayer',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 61, max: 81, speed: 1.7, weaponType: 'dagger', weaponLevel: 2, dagger: true },
    stats: { agi: 8 },
    sellValue: 900,
    requiredClass: ['thief', 'archer'],
  },
  drogmar_warboots: {
    id: 'drogmar_warboots',
    name: "Drogmar's Warboots",
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 2 },
    sellValue: 950,
    requiredClass: ['swordman'],
  },
  ironvein_pickblade: {
    id: 'ironvein_pickblade',
    name: 'Ironvein Pickblade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 65, max: 86, speed: 1.8, weaponType: 'dagger', weaponLevel: 2, dagger: true },
    stats: { agi: 7, vit: 2 },
    sellValue: 950,
    requiredClass: ['thief', 'archer'],
  },
  ironvein_lantern_staff: {
    id: 'ironvein_lantern_staff',
    name: 'Ironvein Lantern Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 38, max: 50, speed: 3.0, weaponType: 'rod', weaponLevel: 2 },
    stats: { int: 7, luk: 3 },
    sellValue: 950,
    requiredClass: ['mage', 'acolyte'],
  },
  marrowlord_boneboots: {
    id: 'marrowlord_boneboots',
    name: 'Marrowlord Boneboots',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 2 },
    sellValue: 1050,
    requiredClass: ['swordman'],
  },
  // Brutok Skullsmasher (rare ogre), guaranteed trophy + warbelt
  skullsmasher_warbelt: {
    id: 'skullsmasher_warbelt',
    name: "Skullsmasher's Warbelt",
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 2 },
    sellValue: 1050,
  },
  // Voskar the Emberwing drops (rare elite dragonkin)
  emberwing_cinderscale: {
    id: 'emberwing_cinderscale',
    name: 'Emberwing Cinderscale',
    kind: 'junk',
    quality: 'common',
    sellValue: 320,
  },
  emberwing_legguards: {
    id: 'emberwing_legguards',
    name: 'Emberwing Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'rare',
    stats: { armor: 3 },
    sellValue: 2200,
    requiredClass: ['swordman'],
  },
  emberfang_warblade: {
    id: 'emberfang_warblade',
    name: 'Emberfang Warblade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    cardSlots: 1,
    weapon: { min: 85, max: 113, speed: 2.5, weaponType: 'sword', weaponLevel: 2, element: 'fire' },
    stats: { str: 8, vit: 3 },
    sellValue: 2400,
    requiredClass: ['swordman', 'thief', 'archer'],
  },
  // --- quest & dungeon blues (rare) ---
  // Brutok Skullsmasher chase weapons (mutually exclusive: brutok_chase)
  brutoks_maul: {
    id: 'brutoks_maul',
    name: "Brutok's Maul",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 92, max: 123, speed: 2.7, weaponType: 'mace', weaponLevel: 3 },
    stats: { str: 8, vit: 3 },
    sellValue: 2000,
    requiredClass: ['swordman', 'thief', 'archer'],
  },
  crag_warden_cudgel: {
    id: 'crag_warden_cudgel',
    name: 'Crag Warden Cudgel',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 91, max: 121, speed: 3.0, weaponType: 'mace', weaponLevel: 3 },
    stats: { int: 8, luk: 4 },
    sellValue: 2000,
    requiredClass: ['mage', 'acolyte'],
  },
  skullsplitter_dirk: {
    id: 'skullsplitter_dirk',
    name: 'Skullsplitter Dirk',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 68, max: 91, speed: 1.7, weaponType: 'dagger', weaponLevel: 3, dagger: true },
    stats: { agi: 8, vit: 3 },
    sellValue: 2000,
    requiredClass: ['thief', 'archer'],
  },
  drogmars_skullcleaver: {
    id: 'drogmars_skullcleaver',
    name: "Drogmar's Skullcleaver",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 87, max: 116, speed: 2.6, weaponType: 'axe', weaponLevel: 3 },
    stats: { str: 7, vit: 4 },
    sellValue: 2000,
    requiredClass: ['swordman', 'thief', 'archer'],
  },
  ogre_bonecharm_staff: {
    id: 'ogre_bonecharm_staff',
    name: 'Ogre Bonecharm Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    cardSlots: 1,
    weapon: { min: 42, max: 56, speed: 3.0, weaponType: 'rod', weaponLevel: 2 },
    stats: { int: 9, luk: 4 },
    sellValue: 2000,
    requiredClass: ['mage', 'acolyte'],
  },
  gutripper_shiv: {
    id: 'gutripper_shiv',
    name: 'Gutripper Shiv',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 67, max: 89, speed: 1.7, weaponType: 'dagger', weaponLevel: 3, dagger: true },
    stats: { agi: 8, vit: 3 },
    sellValue: 2000,
    requiredClass: ['thief', 'archer'],
  },
  stormshard_leggings: {
    id: 'stormshard_leggings',
    name: 'Stormshard Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'rare',
    stats: { armor: 2 },
    sellValue: 1800,
  },
  korgaths_chainwraps: {
    id: 'korgaths_chainwraps',
    name: "Korgath's Chainwraps",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'rare',
    stats: { armor: 3 },
    sellValue: 2200,
  },
  boneguard_breastplate: {
    id: 'boneguard_breastplate',
    name: 'Boneguard Breastplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'rare',
    cardSlots: 2,
    stats: { armor: 5 },
    sellValue: 2500,
    requiredClass: ['swordman'],
  },
  staff_of_velkhar: {
    id: 'staff_of_velkhar',
    name: 'Staff of Velkhar',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 46, max: 61, speed: 3.0, weaponType: 'rod', weaponLevel: 3 },
    stats: { int: 9, luk: 4 },
    sellValue: 2500,
    requiredClass: ['mage', 'acolyte'],
  },
  shadowmeld_tunic: {
    id: 'shadowmeld_tunic',
    name: 'Nightveil Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'rare',
    stats: { armor: 5 },
    sellValue: 2500,
    requiredClass: ['thief', 'archer'],
  },
  gravewyrm_scale_hauberk: {
    id: 'gravewyrm_scale_hauberk',
    name: 'Gravewyrm Scale Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'rare',
    stats: { mdef: 4, armor: 4 },
    sellValue: 3000,
    requiredClass: ['swordman'],
  },
  wyrmcult_grand_robe: {
    id: 'wyrmcult_grand_robe',
    name: 'Wyrmcult Grand Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'rare',
    stats: { mdef: 3, armor: 4 },
    sellValue: 3000,
    requiredClass: ['mage', 'acolyte'],
  },
  wyrmscale_jerkin: {
    id: 'wyrmscale_jerkin',
    name: 'Wyrmscale Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'rare',
    stats: { armor: 4 },
    sellValue: 3000,
    requiredClass: ['thief', 'archer'],
  },
  gravewyrm_stalkers_treads: {
    id: 'gravewyrm_stalkers_treads',
    name: "Gravewyrm Stalker's Treads",
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'rare',
    cardSlots: 1,
    stats: { mdef: 5, armor: 4 },
    sellValue: 3200,
    requiredClass: ['thief', 'archer'],
  },
  gravewyrm_sabatons: {
    id: 'gravewyrm_sabatons',
    name: 'Gravewyrm Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 4 },
    sellValue: 3200,
    requiredClass: ['swordman'],
  },
  wyrmcult_soulsteps: {
    id: 'wyrmcult_soulsteps',
    name: 'Wyrmcult Soulsteps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'rare',
    cardSlots: 1,
    stats: { armor: 3 },
    sellValue: 3200,
    requiredClass: ['mage', 'acolyte'],
  },
  deathlord_warplate: {
    id: 'deathlord_warplate',
    set: 'deathlord',
    name: 'Barrowlord Warplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 5, vit: 3, str: 2 },
    sellValue: 9000,
    requiredClass: ['swordman'],
  },
  necromancers_starshroud: {
    id: 'necromancers_starshroud',
    set: 'necromancers',
    name: 'Mournweave Starshroud',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 4, int: 3, luk: 2 },
    sellValue: 9000,
    requiredClass: ['mage', 'acolyte'],
  },
  wyrmshadow_harness: {
    id: 'wyrmshadow_harness',
    set: 'wyrmshadow',
    name: 'Nightfang Harness',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    cardSlots: 1,
    stats: { mdef: 4, armor: 5, agi: 3, vit: 2 },
    sellValue: 9000,
    requiredClass: ['thief', 'archer'],
  },
  deathlord_legguards: {
    id: 'deathlord_legguards',
    set: 'deathlord',
    name: 'Barrowlord Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 4, str: 3, vit: 3 },
    sellValue: 9000,
    requiredClass: ['swordman'],
  },
  deathlord_sabatons: {
    id: 'deathlord_sabatons',
    set: 'deathlord',
    name: 'Barrowlord Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    cardSlots: 1,
    stats: { mdef: 1, armor: 4, vit: 3, str: 2 },
    sellValue: 9000,
    requiredClass: ['swordman'],
  },
  necromancers_soulsteps: {
    id: 'necromancers_soulsteps',
    set: 'necromancers',
    name: 'Mournweave Soulsteps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 3, int: 3, luk: 2 },
    sellValue: 9000,
    requiredClass: ['mage', 'acolyte'],
  },
  necromancers_legwraps: {
    id: 'necromancers_legwraps',
    set: 'necromancers',
    name: 'Mournweave Legwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 3, int: 3, luk: 2 },
    sellValue: 9000,
    requiredClass: ['mage', 'acolyte'],
  },
  wyrmshadow_treads: {
    id: 'wyrmshadow_treads',
    set: 'wyrmshadow',
    name: 'Nightfang Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 4, agi: 3, vit: 2 },
    sellValue: 9000,
    requiredClass: ['thief', 'archer'],
  },
  wyrmshadow_legguards: {
    id: 'wyrmshadow_legguards',
    set: 'wyrmshadow',
    name: 'Nightfang Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    stats: { armor: 3, agi: 3, vit: 2 },
    sellValue: 9000,
    requiredClass: ['thief', 'archer'],
  },
  // --- the three epics (Korzul drops) ---
  wyrmfang_greatblade: {
    id: 'wyrmfang_greatblade',
    name: 'Wyrmfang Greatblade',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    cardSlots: 2,
    // 2H dps premium: weaponDpsBudget(26) = 14.5 x TWOHAND_DPS_MULT -> 16.7 dps
    // (this pre-dated the Eastbrook/Highwatch rule and sat on the flat curve).
    weapon: { min: 123, max: 164, speed: 2.6, weaponType: 'twohand_sword', weaponLevel: 3 },
    // v0.27.1 re-budget: round(primaryStatBudget(26, epic, mainhand) = 18 x
    // TWOHAND_STAT_MULT) = 23 points; a 2H's compensation lives on the dps side.
    stats: { str: 14, vit: 9 },
    sellValue: 8000,
    requiredClass: ['swordman', 'archer'],
  },
  staff_of_the_gravewyrm: {
    id: 'staff_of_the_gravewyrm',
    name: 'Staff of the Gravewyrm',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 52, max: 69, speed: 3.0, weaponType: 'rod', weaponLevel: 3, element: 'shadow' },
    stats: { int: 12, luk: 6 },
    sellValue: 8000,
    requiredClass: ['mage', 'acolyte'],
  },
  fang_of_korzul: {
    id: 'fang_of_korzul',
    name: 'Fang of Korzul',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 83, max: 110, speed: 1.7, weaponType: 'dagger', weaponLevel: 3, dagger: true },
    stats: { agi: 12, vit: 6 },
    sellValue: 8000,
    requiredClass: ['thief', 'archer'],
  },
  // --- Inventory 2.0 epics: one per armor archetype, filling the new slots and
  // named into the existing Barrowlord/Mournweave/Nightfang Korzul epic families.
  // Stat budget is slot-weighted off the item-level formula (src/sim/item_level.ts),
  // so each lands a notch under its chest epic and slots cleanly into its set. ---
  deathlords_dread_visage: {
    id: 'deathlords_dread_visage',
    set: 'deathlord',
    name: 'Barrowlord Dread Visage',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 5, vit: 3, str: 2 },
    sellValue: 9000,
    requiredClass: ['swordman'],
  },
  necromancers_soulspire_mantle: {
    id: 'necromancers_soulspire_mantle',
    set: 'necromancers',
    name: 'Mournweave Soulspire Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'back',
    quality: 'epic',
    cardSlots: 3,
    stats: { armor: 3, int: 3, luk: 2 },
    sellValue: 9000,
    requiredClass: ['mage', 'acolyte'],
  },
  wyrmshadow_talongrips: {
    id: 'wyrmshadow_talongrips',
    set: 'wyrmshadow',
    name: 'Nightfang Talongrips',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    cardSlots: 1,
    stats: { agi: 3, vit: 1 },
    sellValue: 9000,
    requiredClass: ['thief', 'archer'],
  },
  // --- Thunzharr, the Waking Peak (world boss): epic GLOVES that extend the
  // Tier-2 set families to a third piece. Named and stat-shaped to match each
  // family's existing helm/shoulder. The `set` tag wires each into its family. ---
  crownforged_gauntlets: {
    id: 'crownforged_gauntlets',
    name: 'Bonewrought Gauntlets',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    cardSlots: 1,
    stats: { str: 2, vit: 2 },
    sellValue: 3600,
    requiredClass: ['swordman'],
    set: 'crownforged', // 3rd Bonewrought piece, unlocks the set's 3-piece bonus
  },
  nighttalon_grips: {
    id: 'nighttalon_grips',
    name: 'Direfang Grips',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    cardSlots: 1,
    stats: { agi: 2, vit: 2 },
    sellValue: 3600,
    requiredClass: ['thief', 'archer'],
    set: 'nighttalon', // 3rd Direfang piece, unlocks the set's 3-piece bonus
  },
  soulflame_gloves: {
    id: 'soulflame_gloves',
    name: 'Wraithfire Gloves',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    cardSlots: 3,
    stats: { int: 2, vit: 2 },
    sellValue: 3600,
    requiredClass: ['mage', 'acolyte'],
    set: 'soulflame', // 3rd Wraithfire piece, unlocks the set's 3-piece bonus
  },
  stormcallers_handguards: {
    id: 'stormcallers_handguards',
    name: 'Galecall Handguards',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    cardSlots: 2,
    stats: { int: 2, vit: 2 },
    sellValue: 3600,
    requiredClass: [],
    set: 'stormcallers', // 3rd Galecall piece, unlocks the set's 3-piece bonus
  },
  // --- Thunzharr, the Waking Peak (world boss): epic BELTS, each family's fourth
  // piece (helm, shoulder, glove, belt), alongside the glove drops above. ---
  crownforged_girdle: {
    id: 'crownforged_girdle',
    name: 'Bonewrought Girdle',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    cardSlots: 1,
    stats: { vit: 2, str: 2 },
    sellValue: 3600,
    requiredClass: ['swordman'],
    set: 'crownforged',
  },
  nighttalon_waistband: {
    id: 'nighttalon_waistband',
    name: 'Direfang Waistband',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    cardSlots: 1,
    stats: { agi: 2, vit: 2 },
    sellValue: 3600,
    requiredClass: ['thief', 'archer'],
    set: 'nighttalon',
  },
  soulflame_cord: {
    id: 'soulflame_cord',
    name: 'Wraithfire Cord',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    cardSlots: 1,
    stats: { int: 2, luk: 2 },
    sellValue: 3600,
    requiredClass: ['mage', 'acolyte'],
    set: 'soulflame',
  },
  stormcallers_waistguard: {
    id: 'stormcallers_waistguard',
    name: 'Galecall Waistguard',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    cardSlots: 2,
    stats: { int: 2, vit: 2 },
    sellValue: 3600,
    requiredClass: [],
    set: 'stormcallers',
  },
  deathless_heartwood: {
    id: 'deathless_heartwood',
    name: 'Heartwood of the Deathless Crown',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'legendary',
    cardSlots: 4,
    weapon: { min: 63, max: 84, speed: 3.2, weaponType: 'rod', weaponLevel: 4, element: 'shadow' },
    // A druid caster/healer staff by deliberate choice: its 17 points sit in
    // spirit (druid mana/healing) rather than agility, accepting that feral
    // wearers lose real value from the swap (bear-form AP scales on agility).
    // Hunters/rogues cannot equip it. Still exactly on the 44-pt legendary
    // mainhand budget.
    stats: { luk: 17, vit: 13, int: 14 },
    sellValue: 25000,
    requiredClass: ['mage', 'acolyte'],
    // Life and decay: a damaging spell may fester a nature DoT (Deathbloom); a heal
    // may bloom a nature heal-over-time on its target (Lifebloom).
    weaponProcs: [
      {
        id: 'deathbloom',
        name: 'Deathbloom',
        trigger: 'spellDamage',
        chance: 0.15,
        effects: [
          {
            kind: 'dot',
            name: 'Deathbloom',
            school: 'nature',
            perTick: 12,
            interval: 2,
            duration: 8,
          },
        ],
      },
      {
        id: 'lifebloom',
        name: 'Lifebloom',
        trigger: 'heal',
        chance: 0.15,
        effects: [{ kind: 'hot', name: 'Lifebloom', perTick: 10, interval: 2, duration: 8 }],
      },
    ],
  },
  kingsbane_last_oath: {
    id: 'kingsbane_last_oath',
    name: 'Thronebane, Last Oath of Thornpeak',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'legendary',
    cardSlots: 3,
    weapon: {
      min: 126,
      max: 168,
      speed: 2.8,
      weaponType: 'sword',
      weaponLevel: 4,
      element: 'holy',
    },
    // Rebalanced into a str/agi/sta hybrid within the fixed 44-pt legendary
    // mainhand budget: 15 agi makes it a viable archer ranged weapon (ranged AP +
    // crit) while it stays usable by its swordman/paladin owners.
    stats: { str: 15, agi: 15, vit: 14 },
    sellValue: 25000,
    requiredClass: ['swordman', 'thief', 'archer'],
    // Thunderfury-style on-hit: a nature arc that blasts the target and chains to
    // nearby foes, and slows the primary target's attack speed.
    weaponProcs: [
      {
        id: 'thronebane_arc',
        name: 'Chain Arc',
        // Fires on any weapon strike: a melee swing for its swordman/paladin owners,
        // or a archer's Auto Shot (which shoots this same weapon).
        trigger: 'weaponHit',
        chance: 0.1,
        effects: [
          { kind: 'chainArc', school: 'nature', damage: 42, jumps: 3, falloff: 0.6, radius: 8 },
          { kind: 'attackSlow', name: 'Thunderclap', mult: 1.2, duration: 6 },
        ],
      },
    ],
  },
  crownforged_dreadhelm: {
    id: 'crownforged_dreadhelm',
    set: 'crownforged',
    name: 'Bonewrought Dreadhelm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    stats: { mdef: 1, armor: 5, vit: 3, str: 2 },
    // ilvl-29 raid seed rating (20 -> 2.0%); the Heroic raid variant scales this up
    // and adds a complementary secondary (heroic_variants.ts). Off the stat budget.
    hitRating: 20,
    sellValue: 12000,
    requiredClass: ['swordman'],
  },
  crownforged_warspaulders: {
    id: 'crownforged_warspaulders',
    set: 'crownforged',
    name: 'Bonewrought Warspaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'back',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 5, vit: 3, str: 2 },
    hitRating: 20,
    sellValue: 12000,
    requiredClass: ['swordman'],
  },
  nighttalon_crown: {
    id: 'nighttalon_crown',
    set: 'nighttalon',
    name: 'Direfang Crown',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    stats: { armor: 4, agi: 3, vit: 2 },
    hitRating: 20,
    sellValue: 12000,
    requiredClass: ['thief', 'archer'],
  },
  nighttalon_shoulderguards: {
    id: 'nighttalon_shoulderguards',
    set: 'nighttalon',
    name: 'Direfang Shoulderguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'back',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 4, agi: 3, vit: 2 },
    hitRating: 20,
    sellValue: 12000,
    requiredClass: ['thief', 'archer'],
  },
  soulflame_cowl: {
    id: 'soulflame_cowl',
    set: 'soulflame',
    name: 'Wraithfire Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    cardSlots: 1,
    stats: { armor: 4, int: 3, vit: 2 },
    hitRating: 20,
    sellValue: 12000,
    requiredClass: ['mage', 'acolyte'],
  },
  soulflame_mantle: {
    id: 'soulflame_mantle',
    set: 'soulflame',
    name: 'Wraithfire Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'back',
    quality: 'epic',
    cardSlots: 2,
    stats: { armor: 3, int: 3, vit: 2 },
    hitRating: 20,
    sellValue: 12000,
    requiredClass: ['mage', 'acolyte'],
  },
  stormcallers_crown: {
    id: 'stormcallers_crown',
    set: 'stormcallers',
    name: 'Galecall Crown',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    cardSlots: 3,
    stats: { armor: 5, int: 3, vit: 2 },
    critRating: 20,
    sellValue: 12000,
    requiredClass: [],
  },
  stormcallers_spaulders: {
    id: 'stormcallers_spaulders',
    set: 'stormcallers',
    name: 'Galecall Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'back',
    quality: 'epic',
    stats: { armor: 4, int: 3, vit: 2 },
    critRating: 20,
    sellValue: 12000,
    requiredClass: [],
  },
  // --- Nythraxis raid (normal): the missing offhand-slot + two-hander epics.
  // All four register at item level 29 (source 20 + epic 6 + raid 3), the same
  // tier as the set pieces above, and carry the ilvl-29 raid seed rating (one
  // rating at 20, off the stat budget, like every set piece). ---
  bonewrought_greatsword: {
    id: 'bonewrought_greatsword',
    name: 'Bonewrought Greatsword',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    cardSlots: 2,
    // Two-handers trade stats for a slow, heavy swing: weaponDpsBudget(29) = 15.4
    // x TWOHAND_DPS_MULT -> 17.65 dps here.
    weapon: { min: 163, max: 217, speed: 3.4, weaponType: 'twohand_sword', weaponLevel: 4 },
    // v0.27.1 re-budget: round(primaryStatBudget(29, epic, mainhand) = 20 x
    // TWOHAND_STAT_MULT) = 26 points (a mainhand + offhand pair at this tier
    // carries 35, so any dual-wield or shield setup out-stats this).
    stats: { str: 14, vit: 12 },
    // Physical melee identity: Hit, like the crownforged pieces.
    hitRating: 20,
    sellValue: 12000,
    // The swordman weapon group MINUS thief: rogues never equip two-handers
    // (equipment_rules), and requiredClass must honestly list who can equip.
    // The list no longer matches WARRIOR_WEAPON_CLASSES, so it resolves by
    // literal membership.
    requiredClass: ['swordman', 'archer'],
  },
  direfang_greatblade: {
    id: 'direfang_greatblade',
    name: 'Direfang Greatblade',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    cardSlots: 1,
    // Same 2H rules as the Bonewrought Greatsword: weaponDpsBudget(29) x
    // TWOHAND_DPS_MULT -> 17.67 dps at a faster 3.0 swing, same 26-point budget.
    weapon: { min: 146, max: 195, speed: 3.0, weaponType: 'twohand_sword', weaponLevel: 3 },
    stats: { agi: 14, vit: 12 },
    // Physical melee identity: Hit, like the nighttalon pieces.
    hitRating: 20,
    sellValue: 12000,
    // A bespoke archer lock (not a proficiency group): the agi identity is the
    // archer's, and handing it to the thief group would trade away dual wield.
    requiredClass: ['archer'],
  },
  bonewrought_bulwark: {
    id: 'bonewrought_bulwark',
    name: 'Bonewrought Bulwark',
    kind: 'armor',
    armorType: 'mail',
    slot: 'offhand',
    shield: true,
    quality: 'epic',
    cardSlots: 1,
    // Shield armor is ~2x a same-tier epic chest (the common-tier rule:
    // Wallshield 112 vs chain vest 60): the ilvl-29 epic mail chest
    // extrapolates to ~340 (deathlord_warplate 270 at 26, scaled by the 29-tier
    // helm ratio 310/245), so 680 here. blockValue extrapolates the common
    // ladder (buckler 6, Wallshield 14) to the epic tier: 30. Stats are the
    // exact offhand budget, primaryStatBudget(29, epic, offhand) = 15,
    // sta-heavy for the tank identity.
    blockValue: 30,
    stats: { armor: 5, vit: 3, str: 2 },
    // Physical tank identity: Hit (threat), like the crownforged pieces.
    hitRating: 20,
    sellValue: 12000,
    requiredClass: ['swordman'],
  },
  wraithfire_orb: {
    id: 'wraithfire_orb',
    name: 'Wraithfire Orb',
    kind: 'held_offhand',
    slot: 'offhand',
    quality: 'epic',
    cardSlots: 2,
    // Held-in-offhand caster stat stick: no weapon damage, stats on the exact
    // offhand budget, primaryStatBudget(29, epic, offhand) = 15 (the budget
    // model's 0.75x mainhand line), int/spi identity with minor sta.
    stats: { int: 7, luk: 5, vit: 3 },
    // Healer-inclusive spell throughput: crit like the stormcallers pieces,
    // never Hit (heals are not resisted; the Heartwood healer-facing rule).
    critRating: 20,
    sellValue: 12000,
    // The caster weapon-proficiency group list (CASTER_WEAPON_CLASSES); kind
    // held_offhand equips by the literal requiredClass.
    requiredClass: ['mage', 'acolyte'],
  },
  // --- vendor food & drink (Quartermaster Bree) ---
  trail_hardtack: {
    id: 'trail_hardtack',
    name: 'Highwatch Trail Hardtack',
    kind: 'food',
    quality: 'common',
    foodHp: 552,
    sellValue: 75,
    buyValue: 1200,
  },
  meltwater_flask: {
    id: 'meltwater_flask',
    name: 'Meltwater Flask',
    kind: 'drink',
    quality: 'common',
    drinkMana: 672,
    sellValue: 75,
    buyValue: 1200,
  },
  roast_mountain_goat: {
    id: 'roast_mountain_goat',
    name: 'Roast Mountain Goat',
    kind: 'food',
    quality: 'common',
    foodHp: 874,
    sellValue: 150,
    buyValue: 2500,
  },
  glacier_melt: {
    id: 'glacier_melt',
    name: 'Glacier Melt',
    kind: 'drink',
    quality: 'common',
    drinkMana: 900,
    sellValue: 150,
    buyValue: 2500,
  },
  // --- vendor whites (Armorer Hode + Quartermaster Bree) ---
  highwatch_warblade: {
    id: 'highwatch_warblade',
    name: 'Highwatch Warblade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 64, max: 85, speed: 2.3, weaponType: 'sword', weaponLevel: 2 },
    sellValue: 600,
    buyValue: 6000,
  },
  highwatch_greatsword: {
    id: 'highwatch_greatsword',
    name: 'Highwatch Greatsword',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'common',
    cardSlots: 1,
    weapon: { min: 99, max: 132, speed: 3.4, weaponType: 'twohand_sword', weaponLevel: 2 },
    sellValue: 680,
    buyValue: 6800,
  },
  highwatch_wallshield: {
    id: 'highwatch_wallshield',
    name: 'Highwatch Wallshield',
    kind: 'armor',
    armorType: 'mail',
    slot: 'offhand',
    shield: true,
    blockValue: 14,
    quality: 'common',
    stats: { armor: 1 },
    sellValue: 560,
    buyValue: 5600,
    requiredClass: ['swordman'],
  },
  craghorn_staff: {
    id: 'craghorn_staff',
    name: 'Craghorn Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 35, max: 46, speed: 3.0, weaponType: 'rod', weaponLevel: 2 },
    stats: { int: 2 },
    sellValue: 600,
    buyValue: 6000,
  },
  icevein_dirk: {
    id: 'icevein_dirk',
    name: 'Icevein Dirk',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 55, max: 73, speed: 1.8, weaponType: 'dagger', weaponLevel: 2, dagger: true },
    sellValue: 600,
    buyValue: 6000,
  },
  highwatch_breastplate: {
    id: 'highwatch_breastplate',
    name: 'Highwatch Breastplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 2 },
    sellValue: 700,
    buyValue: 7000,
  },
  peakwool_robe: {
    id: 'peakwool_robe',
    name: 'Peakwool Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'common',
    cardSlots: 2,
    stats: { mdef: 1, armor: 1 },
    sellValue: 500,
    buyValue: 5000,
  },
  stalkerhide_jerkin: {
    id: 'stalkerhide_jerkin',
    name: 'Prowlhide Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 2 },
    sellValue: 600,
    buyValue: 6000,
  },
  cragwalker_boots: {
    id: 'cragwalker_boots',
    name: 'Cragwalker Boots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'common',
    cardSlots: 2,
    stats: { armor: 1 },
    sellValue: 400,
    buyValue: 4000,
  },
  windguard_leggings: {
    id: 'windguard_leggings',
    name: 'Windguard Leggings',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'common',
    cardSlots: 1,
    stats: { armor: 1 },
    sellValue: 450,
    buyValue: 4500,
  },
  // --- junk (gray) ---
  ogre_toe_ring: {
    id: 'ogre_toe_ring',
    name: 'Ogre Toe Ring',
    kind: 'junk',
    quality: 'poor',
    sellValue: 25,
  },
  cracked_ogre_tusk: {
    id: 'cracked_ogre_tusk',
    name: 'Cracked Ogre Tusk',
    kind: 'junk',
    quality: 'poor',
    sellValue: 42,
  },
  inert_storm_shard: {
    id: 'inert_storm_shard',
    name: 'Inert Storm Shard',
    kind: 'junk',
    quality: 'poor',
    sellValue: 28,
  },
  frayed_prayer_beads: {
    id: 'frayed_prayer_beads',
    name: 'Frayed Prayer Beads',
    kind: 'junk',
    quality: 'poor',
    sellValue: 30,
  },
  cracked_wyrm_scale: {
    id: 'cracked_wyrm_scale',
    name: 'Cracked Wyrm Scale',
    kind: 'junk',
    quality: 'poor',
    sellValue: 35,
  },
  // --- Class/spec gap fill: the 17-22 band plus endgame caster pieces ---
  // Budgeted via primaryStatBudget(item level, quality, slot); see
  // src/sim/item_budget.ts. The leather int/spi pieces finish the druid caster
  // line (gloves are covered by the crafted duskhide_wraps), the mail int/spi
  // pieces finish the shaman/paladin caster leveling line below the stormbound
  // tier, and the druid-locked two-handers carry the feral weapon ladder to
  // the raid tier (a bespoke druid-only lock: weaponArchetypeForItem returns
  // null for it and canEquipItem falls through to the literal list, see
  // src/sim/equipment_rules.ts).
  wildgrove_cinch: {
    id: 'wildgrove_cinch',
    name: 'Wildgrove Cinch',
    kind: 'armor',
    slot: 'ring',
    quality: 'uncommon',
    cardSlots: 1,
    // Ridge Stalkers (level 14) -> item level 15, waist budget 4.
    stats: { luk: 2 },
    sellValue: 420,
  },
  cragward_pauldrons: {
    id: 'cragward_pauldrons',
    name: 'Cragward Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'back',
    quality: 'uncommon',
    // Old Cragmaw (level 14 rare elite) -> item level 15, shoulder budget 4.
    stats: { armor: 1 },
    sellValue: 450,
  },
  cragthorn_greatstaff: {
    id: 'cragthorn_greatstaff',
    name: 'Cragthorn Greatstaff',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'rare',
    // Old Cragmaw (level 14 rare elite) -> item level 17: 2H stat budget
    // round(primaryStatBudget(17, rare, mainhand) = 10 x TWOHAND_STAT_MULT) =
    // 13, dps on the weaponDpsBudget(17) x TWOHAND_DPS_MULT curve (~13.57 at
    // speed 3.5).
    weapon: { min: 85, max: 113, speed: 3.5, weaponType: 'twohand_rod', weaponLevel: 2 },
    stats: { str: 5, agi: 4, vit: 4 },
    sellValue: 1400,
    requiredClass: FERAL,
  },
  moonbark_vestments: {
    id: 'moonbark_vestments',
    name: 'Moonbark Vestments',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'rare',
    // Deeprock Kobolds (level 15) -> item level 18, chest budget 10.
    stats: { mdef: 3, armor: 4 },
    sellValue: 1600,
  },
  peaksong_helm: {
    id: 'peaksong_helm',
    name: 'Peaksong Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'rare',
    cardSlots: 1,
    // Deeprock Kobolds (level 15) -> item level 18, helmet budget 9.
    stats: { armor: 3 },
    sellValue: 1500,
  },
  stormchant_gauntlets: {
    id: 'stormchant_gauntlets',
    name: 'Stormchant Gauntlets',
    kind: 'armor',
    slot: 'ring',
    quality: 'uncommon',
    // Ironvein Foreman (level 16 rare elite) -> item level 17, gloves budget 5.
    stats: { int: 2 },
    sellValue: 460,
  },
  cragprowl_belt: {
    id: 'cragprowl_belt',
    name: 'Cragprowl Belt',
    kind: 'armor',
    slot: 'ring',
    quality: 'uncommon',
    // Thornpeak Ogres (level 16) -> item level 17, waist budget 5.
    stats: { agi: 2 },
    sellValue: 440,
  },
  stormroot_cowl: {
    id: 'stormroot_cowl',
    name: 'Stormroot Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'rare',
    // Brutok Skullsmasher (level 17 rare elite) -> item level 20, helmet
    // budget 10.
    stats: { armor: 3 },
    sellValue: 1900,
  },
  thunderward_legguards: {
    id: 'thunderward_legguards',
    name: 'Thunderward Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'rare',
    // Warlord Drogmar (level 17 elite boss) -> item level 20, legs budget 10.
    stats: { armor: 3 },
    sellValue: 2000,
  },
  revenantstep_treads: {
    id: 'revenantstep_treads',
    name: 'Revenantstep Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'rare',
    // Ogre Crushers (level 17 elite) -> item level 20, feet budget 7.
    stats: { armor: 3 },
    sellValue: 1700,
  },
  shardfang_grips: {
    id: 'shardfang_grips',
    name: 'Shardfang Grips',
    kind: 'armor',
    slot: 'ring',
    quality: 'rare',
    // Shardlord Kazzix (level 18 rare) -> item level 21, gloves budget 8.
    stats: { agi: 2, vit: 1 },
    sellValue: 1800,
  },
  shardsong_mantle: {
    id: 'shardsong_mantle',
    name: 'Shardsong Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'back',
    quality: 'rare',
    // Wyrmcult Zealots (level 19) -> item level 22, shoulder budget 9.
    stats: { armor: 3 },
    sellValue: 1900,
  },
  wyrmcult_spellgrips: {
    id: 'wyrmcult_spellgrips',
    name: 'Wyrmcult Spellgrips',
    kind: 'armor',
    slot: 'ring',
    quality: 'rare',
    // Wyrmcult Necromancers (level 19) -> item level 22, gloves budget 9.
    stats: { luk: 2, int: 1 },
    sellValue: 1850,
  },
  thornpeak_wildwraps: {
    id: 'thornpeak_wildwraps',
    name: 'Thornpeak Wildwraps',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'rare',
    // Boneclad Revenants (level 19) -> item level 22, legs budget 11.
    stats: { armor: 3 },
    sellValue: 2100,
  },
  stormvotive_hauberk: {
    id: 'stormvotive_hauberk',
    name: 'Stormvotive Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'rare',
    // Voskar Emberwing (level 19 rare elite) -> item level 22, chest budget 12.
    stats: { armor: 5 },
    sellValue: 2400,
  },
  cryptbloom_shoulderguards: {
    id: 'cryptbloom_shoulderguards',
    name: 'Cryptbloom Shoulderguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'back',
    quality: 'rare',
    cardSlots: 1,
    // Corrupted Priest Malric (level 20 rare elite) -> item level 23, shoulder
    // budget 10, matching the same-tier crafted sootscale_mantle.
    stats: { armor: 3 },
    sellValue: 2200,
  },
  gravewyrm_thornmaul: {
    id: 'gravewyrm_thornmaul',
    name: 'Gravewyrm Thornmaul',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'rare',
    // Sanctum Drakonid (level 20 elite) -> item level 23: 2H stat budget
    // round(primaryStatBudget(23, rare, mainhand) = 13 x TWOHAND_STAT_MULT) =
    // 17, dps on the weaponDpsBudget(23) x TWOHAND_DPS_MULT curve (~15.64 at
    // speed 3.6).
    weapon: { min: 97, max: 129, speed: 3.6, weaponType: 'twohand_mace', weaponLevel: 3 },
    stats: { str: 7, agi: 5, vit: 5 },
    sellValue: 3200,
    requiredClass: FERAL,
  },
  vestments_of_the_waking_grove: {
    id: 'vestments_of_the_waking_grove',
    name: 'Vestments of the Waking Grove',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    cardSlots: 1,
    // Thunzharr, Waking Peak (level 20 world boss) -> item level 26, chest
    // budget 18, the caster counterpart to the wyrmshadow_harness on the same
    // boss table.
    stats: { armor: 5, int: 3, luk: 2 },
    sellValue: 8000,
  },
  nightfangs_greatstaff: {
    id: 'nightfangs_greatstaff',
    name: "Nightfang's Greatstaff",
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    cardSlots: 2,
    // Korzul the Gravewyrm (level 20 dungeon final boss) -> item level 26: 2H
    // stat budget round(primaryStatBudget(26, epic, mainhand) = 18 x
    // TWOHAND_STAT_MULT) = 23 (the wyrmfang_greatblade total), dps on the
    // weaponDpsBudget(26) x TWOHAND_DPS_MULT curve (~16.68 at speed 3.6).
    weapon: {
      min: 126,
      max: 168,
      speed: 3.6,
      weaponType: 'twohand_rod',
      weaponLevel: 4,
      element: 'shadow',
    },
    stats: { str: 9, agi: 7, vit: 7 },
    sellValue: 9000,
    requiredClass: FERAL,
  },
  maul_of_the_scourged_wilds: {
    id: 'maul_of_the_scourged_wilds',
    name: 'Maul of the Scourged Wilds',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    cardSlots: 1,
    // Nythraxis (level 20 raid boss) -> item level 29 with the raid bonus: 2H
    // stat budget round(primaryStatBudget(29, epic, mainhand) = 20 x
    // TWOHAND_STAT_MULT) = 26, dps on the weaponDpsBudget(29) x
    // TWOHAND_DPS_MULT curve (~17.71 at speed 3.7). The top rung of the feral
    // ladder, beside the direfang_greatblade on the same boss.
    weapon: { min: 128, max: 170, speed: 3.7, weaponType: 'twohand_mace', weaponLevel: 4 },
    stats: { str: 10, agi: 8, vit: 8 },
    // Every item-level-29 raid epic carries exactly one rating at 20 (the tier
    // ladder pin in tests/combat_rating.test.ts); the maul takes Hit like the
    // direfang_greatblade beside it.
    hitRating: 20,
    sellValue: 14000,
    requiredClass: FERAL,
  },
  // --- Endgame leather caster line (int/spi, druid-only via armorType). These
  // fill the ilvl-26 dungeon tier on Korzul the Gravewyrm's table so balance
  // druids have on-weight options in every slot above the level-22 band. The
  // armorType already gates equips; no requiredClass is needed.
  wildgrowth_leggings: {
    id: 'wildgrowth_leggings',
    name: 'Wildgrowth Leggings',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    cardSlots: 1,
    // Korzul the Gravewyrm (level 20 dungeon final boss) -> item level 26,
    // legs budget 16.
    stats: { armor: 3, int: 3, luk: 2 },
    sellValue: 8000,
  },
  grovewardens_grips: {
    id: 'grovewardens_grips',
    name: "Grovewarden's Grips",
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    // Korzul the Gravewyrm (level 20 dungeon final boss) -> item level 26,
    // gloves budget 13.
    stats: { int: 2, luk: 2 },
    sellValue: 7500,
  },
  verdant_walkers: {
    id: 'verdant_walkers',
    name: 'Verdant Walkers',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    cardSlots: 1,
    // Korzul the Gravewyrm (level 20 dungeon final boss) -> item level 26,
    // feet budget 12.
    stats: { armor: 3, int: 3, luk: 2 },
    sellValue: 7200,
  },
};

// ---------------------------------------------------------------------------
// Static props (rendering + collision share this placement data). Highwatch
// sits on a high plateau (~9 elevation); the lake at (-70,760) stays clear.
// ---------------------------------------------------------------------------
