// Zone 3, Thornpeak Heights (levels 13-20). The Gravecallers serve Korzul
// the Gravewyrm, an ancient dragon sealed beneath the peaks. Highwatch holds
// the wall against ogres, waking elementals, and the open chanting of the
// Wyrmcult at the Gravewyrm Sanctum gates.

import { WORK_ORDER_CADENCE_TICKS } from '../../professions/cadence';
import type {
  CampDef,
  GroundObjectDef,
  ItemDef,
  MobTemplate,
  NpcDef,
  QuestDef,
  ZoneDef,
  ZonePropsDef,
} from '../../types';
import { FERAL } from '../items';

export const ZONE3_MOBS: Record<string, MobTemplate> = {
  // Highwatch practice target: a near-immortal, stationary dummy for testing damage
  // rotations and reading the combat meters. Cap-level with zero armor so the damage
  // it takes is your clean, unmitigated rotation output. Inert (never fights back),
  // drops nothing (you can never really fell it), and pops back up 10s after a death.
  training_dummy: {
    id: 'training_dummy',
    name: 'Training Dummy',
    minLevel: 20,
    maxLevel: 20,
    family: 'humanoid',
    hpBase: 999999,
    hpPerLevel: 0,
    dmgBase: 0,
    dmgPerLevel: 0,
    attackSpeed: 2.0,
    armorPerLevel: 0,
    moveSpeed: 0,
    aggroRadius: 0,
    loot: [], // a practice target: no drops (you can never really fell it)
    scale: 1.4,
    color: 0xb8924a,
    dummy: true,
    respawnSeconds: 10,
  },
  ridge_stalker: {
    id: 'ridge_stalker',
    name: 'Ridge Stalker',
    minLevel: 13,
    maxLevel: 14,
    family: 'beast',
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 1.9,
    armorPerLevel: 14,
    moveSpeed: 8,
    aggroRadius: 11,
    // Rending Claws: the stalker's raking swipes can open a bleeding wound, a
    // refreshing physical DoT (~5 every 3s for 9s). Distinct from poison: it is
    // physical-school, so it bypasses poison cleanses and ignores nature resist.
    bleed: {
      chance: 0.25,
      perTick: 5,
      interval: 3,
      duration: 9,
      name: 'Rending Claws',
      school: 'physical',
    },
    loot: [
      { copper: 60, chance: 1 },
      { itemId: 'ridge_stalker_pelt', chance: 0.6, questId: 'q_stalker_pelts' },
      { itemId: 'ridge_stalker_pelt', chance: 0.6, questId: 'q_stalker_cloaks' },
      { itemId: 'wildgrove_cinch', chance: 0.1 },
    ],
    scale: 0.95,
    color: 0x8c8270,
    componentTags: ['hide', 'claw', 'meat'],
  },
  // The apex of the southern ridge: a grizzled, scar-pelted old cat that has
  // outlived three generations of its pack. A rare elite counterpart to the
  // Ridge Stalkers, met first when climbing into Thornpeak. Reuses existing
  // mechanics only: a rending pounce (aoePulse) and a wounded-beast enrage.
  old_cragmaw: {
    id: 'old_cragmaw',
    name: 'Old Cragmaw',
    minLevel: 14,
    maxLevel: 14,
    family: 'beast',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 7.2,
    hpBase: 320,
    hpPerLevel: 56,
    dmgBase: 16,
    dmgPerLevel: 4.0,
    attackSpeed: 1.7,
    armorPerLevel: 24,
    moveSpeed: 8.6,
    aggroRadius: 13,
    aoePulse: { min: 22, max: 30, radius: 8, every: 9, name: 'Savage Pounce', school: 'physical' },
    enrage: { belowHpPct: 0.35, dmgMult: 1.4, hasteMult: 1.3 },
    loot: [
      { copper: 220, chance: 1 },
      { itemId: 'old_cragmaws_pelt', chance: 1 },
      { itemId: 'cragmaw_huntcord', chance: 0.25 },
      { itemId: 'cragmaw_prowlboots', chance: 0.3 },
      { itemId: 'cragward_pauldrons', chance: 0.25 },
      { itemId: 'cragthorn_greatstaff', chance: 0.2 },
    ],
    scale: 1.3,
    color: 0x6e6453,
    componentTags: ['hide', 'fang', 'claw'],
  },
  deeprock_kobold: {
    id: 'deeprock_kobold',
    name: 'Deeprock Tunneler',
    minLevel: 14,
    maxLevel: 15,
    family: 'burrower',
    hpBase: 60,
    hpPerLevel: 22,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.1,
    armorPerLevel: 18,
    moveSpeed: 7,
    aggroRadius: 10,
    loot: [
      { copper: 65, chance: 1 },
      { itemId: 'glowing_wax', chance: 0.5, questId: 'q_glowing_wax' },
      { itemId: 'tallow_candle', chance: 0.4 },
      { itemId: 'healing_potion', chance: 0.08 },
      // A grindable long-shot at the epic T1 mail boots that also drop from the
      // Ironvein Foreman: a rare per-kill chance so the Deeprock Burrows are a
      // farmable path to the sabatons, not just the Foreman rare.
      { itemId: 'deathlord_sabatons', chance: 0.001 },
      // Rare caster pieces at a grindable long-shot chance, the same pattern
      // as the sabatons above: mail for the shaman/paladin line, leather for
      // the druid line.
      { itemId: 'peaksong_helm', chance: 0.04 },
      { itemId: 'moonbark_vestments', chance: 0.04 },
    ],
    scale: 0.85,
    color: 0x9c7a3c,
    // Jarring Swing: a heavy mining-pick blow knocks the victim off-balance,
    // cutting their dodge for 8s so the tunneler's strikes land more reliably.
    staggerHit: { chance: 0.3, fleeReduction: 20, duration: 8, name: 'Off-Balance' },
  },
  ironvein_foreman: {
    id: 'ironvein_foreman',
    name: 'Ironvein Foreman',
    minLevel: 16,
    maxLevel: 16,
    family: 'burrower',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    // 144 * 25s base = 1 hour, so the epic-mail-boot rare is farmable on a
    // predictable hourly cadence rather than the old 6-hour wait.
    respawnMult: 144,
    hpBase: 420,
    hpPerLevel: 70,
    dmgBase: 19,
    dmgPerLevel: 4.4,
    attackSpeed: 2.0,
    armorPerLevel: 38,
    moveSpeed: 7,
    aggroRadius: 12,
    aoePulse: { min: 28, max: 38, radius: 8, every: 10, name: 'Powder Keg', school: 'fire' },
    summonAdds: { mobId: 'ironvein_sapper', count: 2, atHpPct: [0.5] },
    rally: { radius: 14, every: 12, ap: 40, duration: 10, name: 'Rallying Banner' },
    enrage: { belowHpPct: 0.3, dmgMult: 1.45, hasteMult: 1.3 },
    loot: [
      { copper: 420, chance: 1 },
      { itemId: 'glowing_wax', chance: 1 },
      { itemId: 'ironvein_pickblade', chance: 0.25 },
      { itemId: 'ironvein_lantern_staff', chance: 0.25 },
      { itemId: 'gutripper_shiv', chance: 0.25, rollGroup: 'ironvein_foreman_chase' },
      { itemId: 'deathlord_sabatons', chance: 0.25, rollGroup: 'ironvein_foreman_chase' },
      { itemId: 'stormchant_gauntlets', chance: 0.2 },
    ],
    scale: 1.05,
    color: 0xb0823a,
  },
  ironvein_sapper: {
    id: 'ironvein_sapper',
    name: 'Ironvein Sapper',
    minLevel: 15,
    maxLevel: 16,
    family: 'burrower',
    hpBase: 58,
    hpPerLevel: 20,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.0,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 12,
    smolder: { chance: 0.25, perTick: 5, interval: 3, duration: 12, name: 'Smoldering Fuse' },
    // The sapper's blasting powder clings and smolders: a struck foe catches fire.
    cinder: {
      chance: 0.3,
      perTick: 5,
      interval: 3,
      duration: 12,
      name: 'Cinderburn',
      school: 'fire',
    },
    loot: [],
    scale: 0.85,
    color: 0x8f6b34,
  },
  thornpeak_ogre: {
    id: 'thornpeak_ogre',
    name: 'Thornpeak Ogre',
    minLevel: 15,
    maxLevel: 16,
    family: 'ogre',
    hpBase: 66,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 11,
    concuss: { chance: 0.2, duration: 2, name: 'Concussive Blow' },
    loot: [
      { copper: 75, chance: 1 },
      { itemId: 'ogre_toe_ring', chance: 0.35 },
      { itemId: 'cragprowl_belt', chance: 0.1 },
    ],
    scale: 1.3,
    color: 0x9e7b53,
  },
  ogre_crusher: {
    id: 'ogre_crusher',
    name: 'Thornpeak Crusher',
    minLevel: 16,
    maxLevel: 17,
    family: 'ogre',
    elite: true,
    hpBase: 64,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 12,
    // Disarming Smash: a war-camp crusher's two-handed blow can batter the weapon
    // from your grip, cutting off auto-attack for a few seconds, a real threat to
    // a tank holding the pack. The inverse of the Summoner's Silencing Shriek.
    disarm: { chance: 0.25, duration: 6, name: 'Disarming Smash', school: 'physical' },
    loot: [
      { copper: 200, chance: 1 },
      { itemId: 'ogre_toe_ring', chance: 0.5 },
      { itemId: 'revenantstep_treads', chance: 0.06 },
    ],
    scale: 1.35,
    color: 0x7e5c3e,
  },
  warlord_drogmar: {
    id: 'warlord_drogmar',
    name: 'Warlord Drogmar',
    minLevel: 17,
    maxLevel: 17,
    family: 'ogre',
    elite: true,
    boss: true,
    hpBase: 200,
    hpPerLevel: 30,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.6,
    armorPerLevel: 28,
    moveSpeed: 7,
    aggroRadius: 14,
    aoePulse: { min: 22, max: 30, radius: 10, every: 12, name: 'Ground Slam' },
    // The longer the warlord is left to swing, the harder he hits: every landed
    // blow stokes his Battle Fury, stacking attack power up to a hard cap. A
    // drawn-out fight snowballs, so burn him down or kite him off you to bleed
    // the stacks back off.
    rampage: { ap: 20, maxStacks: 5, duration: 10, name: 'Mounting Rage', school: 'physical' },
    loot: [
      { copper: 2000, chance: 1 },
      { itemId: 'drogmar_warboots', chance: 0.3 },
      { itemId: 'drogmars_skullcleaver', chance: 0.25 },
      { itemId: 'thunderward_legguards', chance: 0.25 },
    ],
    scale: 1.5,
    color: 0x8c3b2e,
  },
  brutok_skullsmasher: {
    // The ogre family's rare elite, a hulking two-fisted mauler that prowls
    // the crags above the Crusher warbands. Slow, heavily armored and brutal:
    // it slams the ground in a physical shockwave and goes berserk when low.
    // Fills the ogre rare gap beside Ironvein Foreman (kobold), Shardlord
    // Kazzix (elemental) and Marrowlord Varkas (undead).
    id: 'brutok_skullsmasher',
    name: 'Brutok Skullsmasher',
    minLevel: 17,
    maxLevel: 17,
    family: 'ogre',
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 432,
    hpBase: 360,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.6,
    attackSpeed: 2.7,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    aoePulse: {
      min: 22,
      max: 30,
      radius: 10,
      every: 10,
      name: 'Skull Smash',
      school: 'physical',
      fx: 'nova',
    },
    enrage: { belowHpPct: 0.3, dmgMult: 1.5, hasteMult: 1.3 },
    loot: [
      { copper: 320, chance: 1 },
      { itemId: 'cracked_ogre_tusk', chance: 1 },
      { itemId: 'skullsmasher_warbelt', chance: 0.3 },
      { itemId: 'brutoks_maul', chance: 0.25, rollGroup: 'brutok_chase' },
      { itemId: 'crag_warden_cudgel', chance: 0.25, rollGroup: 'brutok_chase' },
      { itemId: 'skullsplitter_dirk', chance: 0.25, rollGroup: 'brutok_chase' },
      { itemId: 'stormroot_cowl', chance: 0.2 },
    ],
    scale: 1.45,
    color: 0x6e5235,
  },
  stormcrag_elemental: {
    id: 'stormcrag_elemental',
    name: 'Stormcrag Elemental',
    minLevel: 17,
    maxLevel: 18,
    family: 'elemental',
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 11,
    loot: [
      { copper: 80, chance: 1 },
      { itemId: 'storm_core', chance: 0.55, questId: 'q_shard_cores' },
      { itemId: 'blessed_embers', chance: 0.55, questId: 'q_breaking_the_seal' },
      { itemId: 'inert_storm_shard', chance: 0.4 },
    ],
    scale: 1.1,
    color: 0x5dade2,
    // A touch of the storm's cold numbs the limbs: each landed swing has a
    // chance to slow the victim to half speed for a few seconds.
    chillOnHit: { chance: 0.35, mult: 0.5, duration: 6, name: 'Numbing Chill' },
    // Static Charge: the elemental's storm clings to whatever it strikes, leaving
    // the victim conductive so every spell that lands on them bites deeper,
    // +18% magic damage taken from all attackers for a while.
    spellVuln: { chance: 0.3, amp: 0.18, duration: 10, name: 'Static Charge', school: 'nature' },
  },
  shardlord_kazzix: {
    id: 'shardlord_kazzix',
    name: 'Shardlord Kazzix',
    minLevel: 18,
    maxLevel: 18,
    family: 'elemental',
    rare: true,
    hpBase: 160,
    hpPerLevel: 28,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: [
      { copper: 500, chance: 1 },
      { itemId: 'kazzix_heartshard', chance: 1, questId: 'q_kazzix' },
      { itemId: 'inert_storm_shard', chance: 1 },
      { itemId: 'shardfang_grips', chance: 0.25 },
    ],
    // The Shardlord's rimebound core sheathes its blows in killing cold, leaving
    // a frost burn that gnaws at the victim long after the strike lands.
    frostbite: {
      chance: 0.3,
      perTick: 6,
      interval: 3,
      duration: 12,
      name: 'Winterbite',
      school: 'frost',
    },
    scale: 1.3,
    color: 0xaed6f1,
  },
  wyrmcult_zealot: {
    id: 'wyrmcult_zealot',
    name: 'Wyrmcult Zealot',
    minLevel: 17,
    maxLevel: 19,
    family: 'humanoid',
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    loot: [
      { copper: 90, chance: 1 },
      { itemId: 'wyrmcult_orders', chance: 0.5, questId: 'q_cult_orders' },
      { itemId: 'frayed_prayer_beads', chance: 0.35 },
      { itemId: 'shardsong_mantle', chance: 0.04 },
    ],
    // The zealot's fevered chanting claws at a caster's mind, draining Intellect
    // and shrinking their mana pool for a while.
    enfeeble: { chance: 0.3, int: 12, duration: 12, name: 'Maddening Whisper', school: 'shadow' },
    // The Wyrmcult hoards their master's flame: a branding strike seals away the
    // victim's fire magic so it can never rival the wyrm's, while leaving every
    // other school free (a single-school counterspell, distinct from a full silence).
    lockout: { chance: 0.25, duration: 6, name: 'Wyrmward Sigil', school: 'fire' },
    scale: 1.0,
    color: 0x76448a,
    componentTags: ['cloth'],
  },
  wyrmcult_necromancer: {
    id: 'wyrmcult_necromancer',
    name: 'Wyrmcult Necromancer',
    minLevel: 18,
    maxLevel: 19,
    family: 'humanoid',
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 11,
    loot: [
      { copper: 100, chance: 1 },
      { itemId: 'ritual_phylactery', chance: 0.55, questId: 'q_necromancers' },
      { itemId: 'linen_scrap', chance: 0.3 },
      { itemId: 'wyrmcult_spellgrips', chance: 0.04 },
    ],
    manaBurn: { chance: 0.3, amount: 80, name: 'Mana Sear', school: 'shadow' },
    // Spectral Ward: a shroud of dark wards that lashes back at any caster whose
    // spell strikes the necromancer, the magic-school twin of melee thorns.
    spellReflect: { value: 9, name: 'Spectral Ward', school: 'shadow' },
    scale: 1.0,
    color: 0x533566,
    componentTags: ['cloth'],
  },
  boneclad_revenant: {
    id: 'boneclad_revenant',
    name: 'Boneclad Revenant',
    minLevel: 18,
    maxLevel: 19,
    family: 'undead',
    hpBase: 66,
    hpPerLevel: 23,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.3,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 11,
    enervate: { chance: 0.3, vit: 14, duration: 12, name: 'Soul Siphon', school: 'shadow' },
    loot: [
      { copper: 100, chance: 1 },
      { itemId: 'bone_fragments', chance: 0.6 },
      { itemId: 'runed_bone_shard', chance: 0.7, questId: 'q_nythraxis_restless_dead' },
      // A grindable long-shot at the epic T1 cloth legs that also drop from
      // Marrowlord Varkas: a rare per-kill chance so the bonefields are a
      // farmable path to the legwraps, not just the once-per-respawn rare.
      { itemId: 'necromancers_legwraps', chance: 0.001 },
      { itemId: 'thornpeak_wildwraps', chance: 0.04 },
    ],
    scale: 1.05,
    color: 0xcacfd2,
  },
  fallen_captain_aldren: {
    id: 'fallen_captain_aldren',
    name: 'Fallen Captain Aldren',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    rare: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 4,
    hpBase: 390,
    hpPerLevel: 72,
    dmgBase: 22,
    dmgPerLevel: 4.2,
    attackSpeed: 2.2,
    armorPerLevel: 42,
    moveSpeed: 7.2,
    aggroRadius: 18,
    cleave: { radius: 7, mult: 0.75, name: 'Grave-Cleaver' },
    loot: [
      { copper: 450, chance: 1 },
      { itemId: 'captains_crest', chance: 1, questId: 'q_nythraxis_sealed_crypt' },
      { itemId: 'bone_fragments', chance: 1 },
    ],
    scale: 1.15,
    color: 0xbfc7ca,
  },
  corrupted_priest_malric: {
    id: 'corrupted_priest_malric',
    name: 'Corrupted Priest Malric',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    rare: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 4,
    hpBase: 360,
    hpPerLevel: 68,
    dmgBase: 23,
    dmgPerLevel: 4.3,
    attackSpeed: 2.3,
    armorPerLevel: 26,
    moveSpeed: 6.9,
    aggroRadius: 18,
    manaBurn: { chance: 0.4, amount: 130, name: 'Withered Benediction', school: 'shadow' },
    mendAlly: {
      healMin: 48,
      healMax: 70,
      radius: 14,
      every: 7,
      name: 'Profane Mending',
      school: 'shadow',
    },
    petSpell: { name: 'Mindfracture', school: 'shadow', min: 38, max: 56, range: 28, every: 2.8 },
    aoePulse: {
      min: 28,
      max: 42,
      radius: 16,
      every: 8,
      name: 'Shadow Nova',
      school: 'shadow',
      fx: 'nova',
    },
    loot: [
      { copper: 450, chance: 1 },
      { itemId: 'priests_sigil', chance: 1, questId: 'q_nythraxis_sealed_crypt' },
      { itemId: 'frayed_prayer_beads', chance: 0.5 },
      { itemId: 'cryptbloom_shoulderguards', chance: 0.2 },
    ],
    scale: 1.05,
    color: 0xd5d0e8,
  },
  deathstalker_voss: {
    id: 'deathstalker_voss',
    name: 'Deathstalker Voss',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    rare: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 4,
    hpBase: 410,
    hpPerLevel: 74,
    dmgBase: 24,
    dmgPerLevel: 4.5,
    attackSpeed: 2.1,
    armorPerLevel: 44,
    moveSpeed: 7.4,
    aggroRadius: 18,
    cleave: { radius: 7, mult: 0.7, name: 'Deathstalker Cleave' },
    mortalStrike: {
      chance: 0.45,
      healReduction: 0.5,
      duration: 10,
      name: 'Forgotten Wound',
      school: 'physical',
    },
    loot: [
      { copper: 450, chance: 1 },
      { itemId: 'royal_seal', chance: 1, questId: 'q_nythraxis_sealed_crypt' },
      { itemId: 'bone_fragments', chance: 1 },
    ],
    scale: 1.18,
    color: 0xc7c0b2,
  },
  vision_aldren_warrior: {
    id: 'vision_aldren_warrior',
    name: 'Vision of Captain Aldren',
    minLevel: 20,
    maxLevel: 20,
    family: 'humanoid',
    hpBase: 1,
    hpPerLevel: 0,
    dmgBase: 0,
    dmgPerLevel: 0,
    attackSpeed: 2,
    armorPerLevel: 0,
    moveSpeed: 0,
    aggroRadius: 0,
    loot: [],
    scale: 1.0,
    color: 0xb8d7ff,
  },
  vision_malric_mage: {
    id: 'vision_malric_mage',
    name: 'Vision of High Priest Malric',
    minLevel: 20,
    maxLevel: 20,
    family: 'humanoid',
    hpBase: 1,
    hpPerLevel: 0,
    dmgBase: 0,
    dmgPerLevel: 0,
    attackSpeed: 2,
    armorPerLevel: 0,
    moveSpeed: 0,
    aggroRadius: 0,
    loot: [],
    scale: 1.0,
    color: 0xc9b6ff,
  },
  vision_deathstalker_voss: {
    id: 'vision_deathstalker_voss',
    name: 'Vision of Royal Assassin Voss',
    minLevel: 20,
    maxLevel: 20,
    family: 'humanoid',
    hpBase: 1,
    hpPerLevel: 0,
    dmgBase: 0,
    dmgPerLevel: 0,
    attackSpeed: 2,
    armorPerLevel: 0,
    moveSpeed: 0,
    aggroRadius: 0,
    loot: [],
    scale: 1.0,
    color: 0xb8d7ff,
  },
  bound_guardian: {
    id: 'bound_guardian',
    name: 'The Bound Guardian',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    boss: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 1000,
    hpBase: 310,
    hpPerLevel: 48,
    dmgBase: 16,
    dmgPerLevel: 3.4,
    attackSpeed: 2.4,
    armorPerLevel: 42,
    moveSpeed: 6.8,
    aggroRadius: 16,
    aoePulse: {
      min: 30,
      max: 44,
      radius: 10,
      every: 10,
      name: 'Sealbreak Shockwave',
      school: 'shadow',
    },
    summonAdds: { mobId: 'varkas_boneguard', count: 2, atHpPct: [0.5] },
    enrage: { belowHpPct: 0.25, dmgMult: 1.45, hasteMult: 1.25 },
    loot: [
      { copper: 1200, chance: 1 },
      { itemId: 'kings_signet', chance: 1, questId: 'q_nythraxis_bound_guardian' },
    ],
    scale: 1.35,
    color: 0xa8b0b8,
  },
  marrowlord_varkas: {
    id: 'marrowlord_varkas',
    name: 'Marrowlord Varkas',
    minLevel: 19,
    maxLevel: 19,
    family: 'undead',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    // 144 * 25s base = 1 hour, so the epic-cloth-leg rare is farmable on a
    // predictable hourly cadence rather than the old 6-hour wait.
    respawnMult: 144,
    hpBase: 480,
    hpPerLevel: 80,
    dmgBase: 22,
    dmgPerLevel: 5.0,
    attackSpeed: 2.4,
    armorPerLevel: 44,
    moveSpeed: 6.5,
    aggroRadius: 13,
    aoePulse: { min: 30, max: 42, radius: 11, every: 9, name: 'Marrow Rot', school: 'shadow' },
    summonAdds: { mobId: 'varkas_boneguard', count: 2, atHpPct: [0.66, 0.33] },
    knockback: { chance: 0.25, distance: 6, name: 'Crushing Sweep' },
    stoneskin: { amount: 260, every: 14, duration: 8, name: 'Bone Carapace', school: 'shadow' },
    loot: [
      { copper: 650, chance: 1 },
      { itemId: 'bone_fragments', chance: 1 },
      { itemId: 'marrowlord_boneboots', chance: 0.3 },
      { itemId: 'necromancers_legwraps', chance: 0.25, rollGroup: 'marrowlord_varkas_chase' },
    ],
    scale: 1.25,
    color: 0xd8d0bd,
  },
  varkas_boneguard: {
    id: 'varkas_boneguard',
    name: 'Varkas Boneguard',
    minLevel: 18,
    maxLevel: 19,
    family: 'undead',
    hpBase: 64,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.8,
    attackSpeed: 2.3,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 12,
    // Shattering Maul: a landed hit can crack the victim's guard, leaving them
    // taking +18% physical damage from every attacker for 8s.
    expose: { chance: 0.25, dmgIncrease: 0.18, duration: 8, name: 'Cracked Guard' },
    loot: [],
    scale: 1.0,
    color: 0xc9c2b5,
  },
  // Voskar the Emberwing, a young drake the Wyrmcult chained above the Sanctum
  // and starved into a weapon. The only dragonkin rare on the peaks: it breathes
  // fire in a wide cone, and its searing bite leaves wounds that refuse to close.
  voskar_emberwing: {
    id: 'voskar_emberwing',
    name: 'Voskar the Emberwing',
    minLevel: 19,
    maxLevel: 19,
    family: 'dragonkin',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 864,
    hpBase: 470,
    hpPerLevel: 78,
    dmgBase: 22,
    dmgPerLevel: 4.9,
    attackSpeed: 2.5,
    armorPerLevel: 42,
    moveSpeed: 7,
    aggroRadius: 13,
    aoePulse: {
      min: 30,
      max: 44,
      radius: 10,
      every: 9,
      name: 'Ember Breath',
      school: 'fire',
      fx: 'nova',
    },
    // Searing Maw: the drake's molten bite cauterizes flesh shut, blunting healing.
    mortalStrike: {
      chance: 0.35,
      healReduction: 0.5,
      duration: 8,
      name: 'Searing Maw',
      school: 'fire',
    },
    enrage: { belowHpPct: 0.3, dmgMult: 1.5, hasteMult: 1.3 },
    loot: [
      { copper: 700, chance: 1 },
      { itemId: 'emberwing_cinderscale', chance: 1 },
      { itemId: 'emberwing_legguards', chance: 0.25, rollGroup: 'voskar_emberwing_chase' },
      { itemId: 'emberfang_warblade', chance: 0.25, rollGroup: 'voskar_emberwing_chase' },
      { itemId: 'stormvotive_hauberk', chance: 0.2 },
    ],
    scale: 1.3,
    color: 0xe8702a,
  },
  // Thunzharr, the Waking Peak: the world boss of Thornpeak Heights. The
  // mountain at Stormcrag is no mountain at all: a primordial storm elemental the
  // Gravecallers' chanting keeps stirring loose. It rises on a fixed cadence (see
  // src/sim/world_boss.ts), bellows a server-wide warning, and rewards every player
  // who helps bring it down with personal loot (once per day). A genuine raid-tier
  // overworld fight: Thunderclap nova, a quaking stomp, summoned stormlings, a
  // crushing heave, a mountain-hide barrier, and a hard enrage in the last fifth.
  thunzharr_waking_peak: {
    id: 'thunzharr_waking_peak',
    name: 'Thunzharr, the Waking Peak',
    minLevel: 20,
    maxLevel: 20,
    family: 'elemental',
    worldBoss: true,
    boss: true,
    elite: true,
    canSwim: false,
    // The mountain does not path around camp furniture: every chase step walks
    // the straight line through fences, buildings, and the waterline, so he can
    // always go directly at his target and never wedges on a collider.
    phasesThroughObstacles: true,
    // His only periodic voice is the battle cry below (every ~45s, zone-wide). The
    // per-mechanic log barks ("unleashes Seismic Stomp/Tectonic Heave/Mountainhide!"
    // and "becomes enraged!") are silenced so an overworld pull does not spam the
    // combat log; the mechanics still fire with their spellfx and damage.
    quietMechanics: true,
    ccImmune: true,
    // A raid boss cannot be perma-snared by a wall of Frostbolts / Hamstrings: slows do
    // not stick to him (ccImmune already blocks stun/root/etc; slow is separate).
    slowImmune: true,
    // Raid-tier health: ~20k base at level 20, ~44k after the elite multiplier, a
    // sustained fight for a gathered raid, far above the solo/small-group rares
    // (Varkas and Bound Guardian scale the same way from ~2k / ~1.3k base).
    hpBase: 4000,
    hpPerLevel: 800,
    // Raid-tier melee, tuned to Nythraxis dps parity (content/dungeons.ts): at
    // level 20 after createMob's 1.5x elite multiplier this averages ~375 per
    // 2.4s swing vs Nythraxis ~406 per 2.6s, ~156 melee dps for both, so the
    // pull needs a healed tank exactly like the raid.
    dmgBase: 54,
    dmgPerLevel: 10.3,
    attackSpeed: 2.4,
    armorPerLevel: 46,
    // Faster than a player's base run speed (7, entity.ts): Thunzharr cannot be
    // outrun on foot, so there is no kite even before the Howling Gale snare lands.
    moveSpeed: 11.6,
    aggroRadius: 18,
    aoePulse: {
      min: 36,
      max: 50,
      radius: 12,
      every: 12,
      name: 'Thunderclap',
      school: 'nature',
      fx: 'nova',
    },
    stomp: {
      radius: 11,
      every: 24,
      // A short pin, not a shutdown: at 11.6 vs a base run of 7 the boss closes
      // about 7yd in 1.5s, enough to be on top of anyone caught mid-flight
      // without benching the raid for whole GCDs.
      duration: 1.5,
      min: 18,
      max: 28,
      name: 'Seismic Stomp',
      school: 'nature',
    },
    // Howling Gale: the anti-kite snare. Gale-force winds pin every player within 40yd
    // to 70% move speed for 6s, re-slammed every 5s (so uptime is permanent while you
    // stand in the storm, and the snare lingers if you flee the radius). Unlike the
    // other pulses this one also fires while Thunzharr is CHASING. With the boss now
    // outrunning base run speed (11.6 vs 7) the snare is a second layer: it keeps a
    // sprint-cooldown or speed-buffed runner from opening a gap. A gentle 30% snare,
    // not a hard 80% one: it denies a permanent kite without rooting the raid in place.
    aoeSlow: {
      radius: 40,
      mult: 0.7,
      duration: 6,
      every: 5,
      name: 'Howling Gale',
      school: 'nature',
    },
    summonAdds: { mobId: 'thunzharr_stormling', count: 2, atHpPct: [0.66, 0.33] },
    knockback: { chance: 0.3, distance: 7, name: 'Tectonic Heave' },
    stoneskin: { amount: 500, every: 27, duration: 9, name: 'Mountainhide', school: 'nature' },
    // Stormcall: the telegraphed hardcast. A 3.5s cast bar the whole raid can see
    // (and the yell announces), then a heavy nature nova on everyone within 30yd,
    // roughly double a Thunderclap pulse on a much longer cadence.
    bigCast: {
      castId: 'thunzharr_stormcall',
      name: 'Stormcall',
      castTime: 3.5,
      every: 40,
      radius: 30,
      min: 70,
      max: 90,
      school: 'nature',
      yell: 'The storm answers my call!',
    },
    yells: {
      engage: 'You wake the mountain? Then be buried by it!',
      summon: 'Rise, stormlings! Tear them loose from my slopes!',
      enrage: 'The peak breaks, and the sky falls with it!',
    },
    // Loud: a mountain-sized voice, and (with quietMechanics) his ONLY periodic
    // voice. Every yell (engage/summon/enrage + these battle cries) carries 350yd,
    // far past the 100yd default; he bellows one of these lines about every 45s in
    // combat, so the whole of Thornpeak knows he is awake without the log ever
    // filling with per-mechanic barks.
    battleYells: {
      every: 45,
      range: 350,
      lines: [
        'THUNDER ANSWERS! The peak has teeth again!',
        'Run, little climbers! The mountain runs faster!',
        'Every stone remembers your name, and none forgive!',
        'I am the storm the summit swallowed!',
      ],
    },
    enrage: { belowHpPct: 0.2, dmgMult: 1.5, hasteMult: 1.25 },
    // Personal loot table: rolled INDEPENDENTLY for every contributor (see
    // rollWorldBossLoot). A guaranteed storm trophy, plus AT MOST ONE epic Tier-2 set
    // piece. The glove group rolls first at ~32%; the belt group also rolls at ~32% but
    // the one-gear cap keeps it only when the glove roll missed, so its EFFECTIVE drop
    // rate is ~22% (0.68 x 0.32) and a single kill never hands out both a glove and a belt.
    // Keep the glove entries first if this ordering skew is ever retuned.
    loot: [
      { itemId: 'inert_storm_shard', chance: 1 },
      { itemId: 'crownforged_gauntlets', chance: 0.08, rollGroup: 'thunzharr_t2' },
      { itemId: 'nighttalon_grips', chance: 0.08, rollGroup: 'thunzharr_t2' },
      { itemId: 'soulflame_gloves', chance: 0.08, rollGroup: 'thunzharr_t2' },
      { itemId: 'stormcallers_handguards', chance: 0.08, rollGroup: 'thunzharr_t2' },
      { itemId: 'crownforged_girdle', chance: 0.08, rollGroup: 'thunzharr_t2_belt' },
      { itemId: 'nighttalon_waistband', chance: 0.08, rollGroup: 'thunzharr_t2_belt' },
      { itemId: 'soulflame_cord', chance: 0.08, rollGroup: 'thunzharr_t2_belt' },
      { itemId: 'stormcallers_waistguard', chance: 0.08, rollGroup: 'thunzharr_t2_belt' },
      { itemId: 'vestments_of_the_waking_grove', chance: 0.08, rollGroup: 'thunzharr_t2' },
    ],
    scale: 8, // a large, imposing world boss that reads on the skyline without being mountain-sized. Visual scale is DECOUPLED from combat reach: his melee is pinned to a ~17yd (scale-5) body in combatProfileForMob (mob_combat.ts), so his move speed and the Howling Gale snare, not a giant swing, are what keep him unkitable.
    color: 0x7d8a99,
  },
  // Stormlings: lesser storm elementals Thunzharr tears loose from itself at the
  // health thresholds above. Fast, fragile, and meant to split a raid's attention.
  thunzharr_stormling: {
    id: 'thunzharr_stormling',
    name: 'Roused Stormling',
    minLevel: 19,
    maxLevel: 20,
    family: 'elemental',
    hpBase: 70,
    hpPerLevel: 24,
    dmgBase: 13,
    dmgPerLevel: 2.9,
    attackSpeed: 2.0,
    armorPerLevel: 22,
    moveSpeed: 7.4,
    aggroRadius: 12,
    loot: [],
    scale: 0.95,
    color: 0x9fb3c8,
  },
};

// ---------------------------------------------------------------------------
// NPCs (Highwatch hub)
// ---------------------------------------------------------------------------
