// Zone 2, Mirefen Marsh (levels 6-13). Brother Aldric follows the
// Gravecaller trail north of the causeway: drowned dead rise from the fen,
// trolls dig into barrow-mounds, and Vael the Fogbinder waits in the
// Sunken Bastion.

import { WORK_ORDER_CADENCE_TICKS } from '../../professions/cadence';
import type {
  CampDef,
  GroundObjectDef,
  ItemDef,
  MobTemplate,
  NpcDef,
  PlayerClass,
  QuestDef,
  ZoneDef,
  ZonePropsDef,
} from '../../types';
import { FERAL } from '../items';

// Archetype groups for class-locked rewards (REWARD_ARCHETYPE hands swordman
// rewards to paladins/shamans etc., so the lock must admit the whole group).
const WAR: PlayerClass[] = ['swordman'];
const MAG: PlayerClass[] = ['mage', 'acolyte'];
const ROG: PlayerClass[] = ['thief', 'archer'];
const CASTER_WEAPON_CLASSES: PlayerClass[] = ['mage', 'acolyte'];

export const ZONE2_ITEMS: Record<string, ItemDef> = {
  // --- quest items ---
  fen_muster_order: {
    id: 'fen_muster_order',
    name: 'Fenbridge Muster Order',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_fenbridge_muster',
  },
  mire_prowler_pelt: {
    id: 'mire_prowler_pelt',
    name: 'Mire Prowler Pelt',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_prowler_pelts',
  },
  lost_caravan_goods: {
    id: 'lost_caravan_goods',
    name: 'Lost Caravan Goods',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_fen_supplies',
  },
  the_codfather: {
    id: 'the_codfather',
    name: 'The Codfather',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_the_codfather',
  },
  waterlogged_idol: {
    id: 'waterlogged_idol',
    name: 'Waterlogged Idol',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_idols',
  },
  widow_venom_sac: {
    id: 'widow_venom_sac',
    name: 'Widow Venom Sac',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_widows',
  },
  rusted_censer: {
    id: 'rusted_censer',
    name: 'Rusted Censer',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_drowned_censers',
  },
  troll_fetish: {
    id: 'troll_fetish',
    name: 'Mirefen Troll Fetish',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_troll_fetishes',
  },
  grubjaw_tusk: {
    id: 'grubjaw_tusk',
    name: "Grubjaw's Tusk",
    kind: 'quest',
    sellValue: 0,
    questId: 'q_grubjaw',
  },
  cult_cipher: {
    id: 'cult_cipher',
    name: 'Gravecaller Cipher',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_summoners',
  },
  bastion_ward_stone: {
    id: 'bastion_ward_stone',
    name: 'Bastion Ward Stone',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_bastion_door',
  },
  unknown_alien_weaponry: {
    id: 'unknown_alien_weaponry',
    name: 'Unknown Alien Weaponry',
    kind: 'quest',
    quality: 'rare',
    sellValue: 0,
    questId: 'q_aldrics_fallen_star',
  },
  // --- quest reward gear (uncommon) ---
  alien_armor_plate: {
    id: 'alien_armor_plate',
    name: 'Alien Armor Plate',
    kind: 'tool',
    quality: 'rare',
    use: { type: 'skinSelect', catalog: 'mech' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  amber_crimson_armor_plate: {
    id: 'amber_crimson_armor_plate',
    name: 'Amber Crimson',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'mechChroma', chromaId: 'amber_crimson' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  crimson_amber_armor_plate: {
    id: 'crimson_amber_armor_plate',
    name: 'Crimson Amber',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'mechChroma', chromaId: 'crimson_amber' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  cyan_magenta_armor_plate: {
    id: 'cyan_magenta_armor_plate',
    name: 'Cyan Magenta',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'mechChroma', chromaId: 'cyan_magenta' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  magenta_cyan_armor_plate: {
    id: 'magenta_cyan_armor_plate',
    name: 'Magenta Cyan',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'mechChroma', chromaId: 'magenta_cyan' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  orange_steel_armor_plate: {
    id: 'orange_steel_armor_plate',
    name: 'Orange Steel',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'mechChroma', chromaId: 'orange_steel' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  steel_orange_armor_plate: {
    id: 'steel_orange_armor_plate',
    name: 'Steel Orange',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'mechChroma', chromaId: 'steel_orange' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  forest_pink_armor_plate: {
    id: 'forest_pink_armor_plate',
    name: 'Forest Pink',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'mechChroma', chromaId: 'forest_pink' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  pink_forest_armor_plate: {
    id: 'pink_forest_armor_plate',
    name: 'Pink Forest',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'mechChroma', chromaId: 'pink_forest' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  amethyst_silver_armor_plate: {
    id: 'amethyst_silver_armor_plate',
    name: 'Amethyst Silver',
    kind: 'tool',
    quality: 'rare',
    use: { type: 'mechChroma', chromaId: 'amethyst_silver' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  ivory_copper_armor_plate: {
    id: 'ivory_copper_armor_plate',
    name: 'Ivory Copper',
    kind: 'tool',
    quality: 'rare',
    use: { type: 'mechChroma', chromaId: 'ivory_copper' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  onyx_gold_armor_plate: {
    id: 'onyx_gold_armor_plate',
    name: 'Onyx Gold',
    kind: 'tool',
    quality: 'rare',
    use: { type: 'mechChroma', chromaId: 'onyx_gold' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  imperial_crimson_armor_plate: {
    id: 'imperial_crimson_armor_plate',
    name: 'Imperial Crimson',
    kind: 'tool',
    quality: 'epic',
    use: { type: 'mechChroma', chromaId: 'imperial_crimson' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  imperial_gold_armor_plate: {
    id: 'imperial_gold_armor_plate',
    name: 'Imperial Gold',
    kind: 'tool',
    quality: 'epic',
    use: { type: 'mechChroma', chromaId: 'imperial_gold' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  vanguard_azure_armor_plate: {
    id: 'vanguard_azure_armor_plate',
    name: 'Vanguard Azure',
    kind: 'tool',
    quality: 'epic',
    use: { type: 'mechChroma', chromaId: 'vanguard_azure' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  vanguard_chrome_armor_plate: {
    id: 'vanguard_chrome_armor_plate',
    name: 'Vanguard Chrome',
    kind: 'tool',
    quality: 'epic',
    use: { type: 'mechChroma', chromaId: 'vanguard_chrome' },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
  deacons_cleaver: {
    id: 'deacons_cleaver',
    name: "Deacon's Cleaver",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 59, max: 79, speed: 2.4, weaponType: 'axe', weaponLevel: 2 },
    stats: { str: 4 },
    sellValue: 300,
    requiredClass: WAR,
  },
  staff_of_drowned_prayers: {
    id: 'staff_of_drowned_prayers',
    name: 'Staff of Drowned Prayers',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 30, max: 40, speed: 3.0, weaponType: 'rod', weaponLevel: 1 },
    stats: { int: 5, luk: 2 },
    sellValue: 300,
    requiredClass: CASTER_WEAPON_CLASSES,
  },
  mistbinder_kris: {
    id: 'mistbinder_kris',
    name: 'Mistbinder Kris',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 47, max: 62, speed: 1.7, weaponType: 'dagger', weaponLevel: 1, dagger: true },
    stats: { agi: 4 },
    sellValue: 300,
    requiredClass: ROG,
  },
  drownedguard_breastplate: {
    id: 'drownedguard_breastplate',
    name: 'Drownedguard Breastplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 130, vit: 4 },
    sellValue: 350,
    requiredClass: WAR,
  },
  fenmist_robe: {
    id: 'fenmist_robe',
    name: 'Fenmist Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 45, int: 5, luk: 3 },
    sellValue: 350,
    requiredClass: MAG,
  },
  eelskin_tunic: {
    id: 'eelskin_tunic',
    name: 'Eelskin Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 80, agi: 5 },
    sellValue: 350,
    requiredClass: ROG,
  },
  trollhide_leggings: {
    id: 'trollhide_leggings',
    name: 'Trollhide Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 55, vit: 3, str: 2 },
    sellValue: 280,
  },
  marshstrider_boots: {
    id: 'marshstrider_boots',
    name: 'Marshstrider Boots',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 40, agi: 2, vit: 2 },
    sellValue: 250,
  },
  broodmother_silk_robe: {
    id: 'broodmother_silk_robe',
    name: "Broodmother's Silk Robe",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 42, int: 4, luk: 2 },
    sellValue: 300,
    requiredClass: MAG,
  },
  voss_sanctified_mace: {
    id: 'voss_sanctified_mace',
    name: "Voss's Sanctified Mace",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 65, max: 86, speed: 2.6, weaponType: 'mace', weaponLevel: 2 },
    stats: { int: 3, luk: 2 },
    sellValue: 420,
    requiredClass: MAG,
  },
  mirejaw_biteblade: {
    id: 'mirejaw_biteblade',
    name: 'Mirejaw Biteblade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 51, max: 68, speed: 1.7, weaponType: 'dagger', weaponLevel: 2, dagger: true },
    stats: { agi: 5, vit: 2 },
    sellValue: 480,
    requiredClass: ROG,
  },
  mirejaw_scale_vest: {
    id: 'mirejaw_scale_vest',
    name: 'Mirejaw Scale Vest',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 115, str: 2, vit: 3 },
    sellValue: 480,
    requiredClass: WAR,
  },
  // --- Sloomtooth the Drowned chase drops (rare) ---
  tidereaver_gaff: {
    id: 'tidereaver_gaff',
    name: 'Tidereaver Gaff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 126, max: 168, speed: 2.5, weaponType: 'spear', weaponLevel: 4 },
    stats: { str: 5, vit: 4 },
    sellValue: 1400,
    requiredClass: WAR,
  },
  sloomtooth_tidefang: {
    id: 'sloomtooth_tidefang',
    name: "Sloomtooth's Tidefang",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 57, max: 76, speed: 1.7, weaponType: 'dagger', weaponLevel: 2, dagger: true },
    stats: { agi: 6, vit: 3 },
    sellValue: 1400,
    requiredClass: ROG,
  },
  drowned_tide_scepter: {
    id: 'drowned_tide_scepter',
    name: 'Drowned Tide Scepter',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 35, max: 47, speed: 3.0, weaponType: 'rod', weaponLevel: 2 },
    stats: { int: 6, luk: 3 },
    sellValue: 1400,
    requiredClass: MAG,
  },
  nhalias_funeral_wraps: {
    id: 'nhalias_funeral_wraps',
    name: "Nhalia's Funeral Wraps",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 48, int: 5, luk: 2 },
    sellValue: 480,
    requiredClass: MAG,
  },
  fen_reaver_glaive: {
    id: 'fen_reaver_glaive',
    name: 'Fen Reaver Glaive',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 113, max: 150, speed: 2.4, weaponType: 'spear', weaponLevel: 3 },
    stats: { str: 5, vit: 3 },
    sellValue: 1400,
    requiredClass: WAR,
  },
  nhalias_dirgeblade: {
    id: 'nhalias_dirgeblade',
    name: "Nhalia's Dirgeblade",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 55, max: 73, speed: 1.7, weaponType: 'dagger', weaponLevel: 2, dagger: true },
    stats: { agi: 6, vit: 3 },
    sellValue: 1400,
    requiredClass: ROG,
  },
  mirejaw_oracle_staff: {
    id: 'mirejaw_oracle_staff',
    name: 'Mirejaw Oracle Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 35, max: 46, speed: 3.0, weaponType: 'rod', weaponLevel: 2 },
    stats: { int: 6, luk: 3 },
    sellValue: 1400,
    requiredClass: CASTER_WEAPON_CLASSES,
  },
  // --- Sunken Bastion blues (rare) ---
  mistcallers_edge: {
    id: 'mistcallers_edge',
    name: "Fogbinder's Edge",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 63, max: 84, speed: 2.3, weaponType: 'sword', weaponLevel: 2 },
    stats: { str: 4, vit: 3 },
    sellValue: 1200,
    requiredClass: WAR,
  },
  vaels_mist_staff: {
    id: 'vaels_mist_staff',
    name: "Vael's Mist-Staff",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 34, max: 45, speed: 3.0, weaponType: 'rod', weaponLevel: 2 },
    stats: { int: 6, luk: 3 },
    sellValue: 1200,
    requiredClass: CASTER_WEAPON_CLASSES,
  },
  riptide_dirk: {
    id: 'riptide_dirk',
    name: 'Riptide Dirk',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 53, max: 70, speed: 1.7, weaponType: 'dagger', weaponLevel: 2, dagger: true },
    stats: { agi: 5, vit: 2 },
    sellValue: 1200,
    requiredClass: ROG,
  },
  knight_commanders_greaves: {
    id: 'knight_commanders_greaves',
    name: "Knight-Commander's Greaves",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'rare',
    stats: { armor: 95, vit: 4 },
    sellValue: 1000,
  },
  tidescale_vest: {
    id: 'tidescale_vest',
    name: 'Tidescale Vest',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'rare',
    stats: { armor: 90, vit: 3, agi: 2 },
    sellValue: 1100,
  },
  tideguard_greaves: {
    id: 'tideguard_greaves',
    name: 'Tideguard Greaves',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'rare',
    stats: { armor: 125, str: 3, vit: 5 },
    sellValue: 1100,
    requiredClass: WAR,
  },
  tideguard_sabatons: {
    id: 'tideguard_sabatons',
    name: 'Tideguard Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 105, str: 2, vit: 4 },
    sellValue: 1100,
    requiredClass: WAR,
  },
  drowned_prayer_leggings: {
    id: 'drowned_prayer_leggings',
    name: 'Drowned Prayer Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'rare',
    stats: { armor: 48, int: 6, luk: 4 },
    sellValue: 1100,
    requiredClass: MAG,
  },
  drowned_prayer_sandals: {
    id: 'drowned_prayer_sandals',
    name: 'Drowned Prayer Sandals',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 42, int: 5, luk: 3 },
    sellValue: 1100,
    requiredClass: MAG,
  },
  eelscale_leggings: {
    id: 'eelscale_leggings',
    name: 'Eelscale Leggings',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'rare',
    stats: { armor: 86, agi: 6, vit: 3 },
    sellValue: 1100,
    requiredClass: ROG,
  },
  eelscale_treads: {
    id: 'eelscale_treads',
    name: 'Eelscale Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 72, agi: 5, vit: 3 },
    sellValue: 1100,
    requiredClass: ROG,
  },
  // --- vendor food & drink (Provisioner Hale) ---
  fenbridge_rye: {
    id: 'fenbridge_rye',
    name: 'Fenbridge Rye Loaf',
    kind: 'food',
    quality: 'common',
    foodHp: 243,
    sellValue: 25,
    buyValue: 400,
  },
  marsh_mint_tea: {
    id: 'marsh_mint_tea',
    name: 'Marsh Mint Tea',
    kind: 'drink',
    quality: 'common',
    drinkMana: 288,
    sellValue: 25,
    buyValue: 400,
  },
  smoked_eel: {
    id: 'smoked_eel',
    name: 'Smoked Mirefen Eel',
    kind: 'food',
    quality: 'common',
    foodHp: 432,
    sellValue: 60,
    buyValue: 1000,
  },
  silvermist_cordial: {
    id: 'silvermist_cordial',
    name: 'Silvermist Cordial',
    kind: 'drink',
    quality: 'common',
    drinkMana: 436,
    sellValue: 60,
    buyValue: 1000,
  },
  // --- vendor white gear (Provisioner Hale) ---
  bogiron_mace: {
    id: 'bogiron_mace',
    name: 'Bogiron Mace',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 55, max: 73, speed: 2.6, weaponType: 'mace', weaponLevel: 1 },
    sellValue: 250,
    buyValue: 2500,
  },
  fenreed_staff: {
    id: 'fenreed_staff',
    name: 'Fenreed Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 27, max: 36, speed: 3.0, weaponType: 'rod', weaponLevel: 1 },
    stats: { int: 1 },
    sellValue: 250,
    buyValue: 2500,
  },
  mirefen_skinner: {
    id: 'mirefen_skinner',
    name: 'Mirefen Skinner',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 43, max: 57, speed: 1.8, weaponType: 'dagger', weaponLevel: 1, dagger: true },
    sellValue: 250,
    buyValue: 2500,
  },
  bogiron_hauberk: {
    id: 'bogiron_hauberk',
    name: 'Bogiron Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 100 },
    sellValue: 300,
    buyValue: 3000,
  },
  marshcloth_robe: {
    id: 'marshcloth_robe',
    name: 'Marshcloth Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 32 },
    sellValue: 200,
    buyValue: 2000,
  },
  reedwoven_jerkin: {
    id: 'reedwoven_jerkin',
    name: 'Reedwoven Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 62 },
    sellValue: 250,
    buyValue: 2500,
  },
  fenwalker_boots: {
    id: 'fenwalker_boots',
    name: 'Fenwalker Boots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'common',
    stats: { armor: 30 },
    sellValue: 150,
    buyValue: 1500,
  },
  reedwoven_trousers: {
    id: 'reedwoven_trousers',
    name: 'Reedwoven Trousers',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'common',
    stats: { armor: 40 },
    sellValue: 180,
    buyValue: 1800,
  },
  // --- junk (gray) ---
  bogiron_nugget: {
    id: 'bogiron_nugget',
    name: 'Bogiron Nugget',
    kind: 'junk',
    quality: 'poor',
    sellValue: 12,
  },
  soggy_moccasin: {
    id: 'soggy_moccasin',
    name: 'Soggy Moccasin',
    kind: 'junk',
    quality: 'poor',
    sellValue: 9,
  },
  cracked_fetish: {
    id: 'cracked_fetish',
    name: 'Cracked Fetish',
    kind: 'junk',
    quality: 'poor',
    sellValue: 14,
  },
  chipped_tusk: {
    id: 'chipped_tusk',
    name: 'Chipped Tusk',
    kind: 'junk',
    quality: 'poor',
    sellValue: 15,
  },
  deepfen_pearl: {
    id: 'deepfen_pearl',
    name: 'Deepfen Pearl',
    kind: 'junk',
    quality: 'poor',
    sellValue: 600,
  },
  // --- Class/spec gap fill (uncommon/green leveling pieces) ---
  // Budgeted via primaryStatBudget(item level, uncommon, slot); see
  // src/sim/item_budget.ts. The leather int/spi pieces continue the druid
  // caster line, the mail int/spi pieces the shaman/paladin caster line, and
  // the druid-locked two-hander is the second rung of the feral weapon ladder
  // (a bespoke druid-only lock: weaponArchetypeForItem returns null for it and
  // canEquipItem falls through to the literal list, src/sim/equipment_rules.ts).
  fenbark_leggings: {
    id: 'fenbark_leggings',
    name: 'Fenbark Leggings',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'uncommon',
    // Sableweb Widows (level 10) -> item level 11, legs budget 4.
    stats: { armor: 48, int: 3, luk: 1 },
    sellValue: 320,
  },
  mirebloom_treads: {
    id: 'mirebloom_treads',
    name: 'Mirebloom Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'uncommon',
    // Mirejaw the Ravenous (level 10 rare elite) -> item level 11, feet budget 3.
    stats: { armor: 28, int: 2, luk: 1 },
    sellValue: 300,
  },
  fenwarden_sabatons: {
    id: 'fenwarden_sabatons',
    name: 'Fenwarden Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'uncommon',
    // Mirefen Broodmother (level 10 boss) -> item level 11, feet budget 3.
    stats: { armor: 42, int: 2, luk: 1 },
    sellValue: 310,
  },
  marshlight_hauberk: {
    id: 'marshlight_hauberk',
    name: 'Marshlight Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    // Mirefen Trolls (level 12) -> item level 13, chest budget 5.
    stats: { armor: 110, int: 3, luk: 2 },
    sellValue: 380,
  },
  duskthorn_mantle: {
    id: 'duskthorn_mantle',
    name: 'Duskthorn Mantle',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'uncommon',
    // Gravecaller Menders (level 12) -> item level 13, shoulder budget 4.
    stats: { armor: 34, int: 3, luk: 1 },
    sellValue: 340,
  },
  fenshadow_maul: {
    id: 'fenshadow_maul',
    name: 'Fenshadow Maul',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'uncommon',
    // Deacon Voss (level 12 boss; also the q_deacon druid reward) -> item level
    // 13: 2H stat budget round(primaryStatBudget(13, uncommon, mainhand) = 5 x
    // TWOHAND_STAT_MULT) = 7, dps on the weaponDpsBudget(13) x TWOHAND_DPS_MULT
    // curve (~12.19 at speed 3.4).
    weapon: { min: 44, max: 59, speed: 3.4, weaponType: 'twohand_mace', weaponLevel: 1 },
    stats: { str: 3, agi: 2, vit: 2 },
    sellValue: 420,
    requiredClass: FERAL,
  },
};

// ---------------------------------------------------------------------------
// Static props (rendering + collision share this placement data)
// ---------------------------------------------------------------------------
