// Zone 2 — Mirefen Marsh (levels 6-13). Brother Aldric follows the
// Gravecaller trail north of the causeway: drowned dead rise from the fen,
// trolls dig into barrow-mounds, and Vael the Fogbinder waits in the
// Sunken Bastion.

import { WORK_ORDER_CADENCE_TICKS } from '../../professions/cadence';
import type {
  CampDef,
  GroundObjectDef,
  ItemDef,
  MobTemplate,
  NpcDef,
  PlayerClass,
  QuestDef,
  ZoneDef,
  ZonePropsDef,
} from '../../types';
import { FERAL } from '../items';

export const ZONE2_MOBS: Record<string, MobTemplate> = {
  mire_prowler: {
    id: 'mire_prowler',
    name: 'Mire Prowler',
    minLevel: 7,
    maxLevel: 8,
    family: 'beast',
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.1,
    attackSpeed: 2.0,
    armorPerLevel: 12,
    moveSpeed: 8.5,
    aggroRadius: 11,
    loot: [
      { copper: 30, chance: 1 },
      { itemId: 'mire_prowler_pelt', chance: 0.6, questId: 'q_prowler_pelts' },
      { itemId: 'soggy_moccasin', chance: 0.3 },
      { itemId: 'lesser_healing_potion', chance: 0.08 },
    ],
    scale: 0.95,
    color: 0x4d5656,
    // Miring Pounce: the prowler drags its prey into the sucking mire, slowing
    // the victim's swings (+30% swing interval) for 8s.
    slowStrike: { chance: 0.3, mult: 1.3, duration: 8, name: 'Miring Pounce', school: 'physical' },
    componentTags: ['hide', 'claw', 'meat'],
  },
  deepfen_murloc: {
    id: 'deepfen_murloc',
    name: 'Deepfen Snapper',
    minLevel: 8,
    maxLevel: 9,
    family: 'mudfin',
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.2,
    attackSpeed: 1.9,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 14, // deepfen packs swarm from far out
    loot: [
      { copper: 35, chance: 1 },
      { itemId: 'waterlogged_idol', chance: 0.5, questId: 'q_idols' },
      { itemId: 'mudfin_scale', chance: 0.4 },
    ],
    scale: 0.85,
    color: 0x45b39d,
    // Acid Spit: a snapper's bite corrodes armor, stacking so a swarm shreds you fast.
    corrode: {
      chance: 0.35,
      armor: 20,
      maxStacks: 5,
      duration: 15,
      name: 'Acid Spit',
      school: 'nature',
    },
    // Tide Cadence: a snapper drums up the school, quickening the whole pack's
    // bites — the swarm's signature pressure when you pull more than one.
    warcry: {
      radius: 12,
      every: 10,
      hasteMult: 1.25,
      duration: 6,
      name: 'Tide Cadence',
      school: 'frost',
    },
    componentTags: ['gills', 'hide'],
  },
  mirejaw_the_ravenous: {
    id: 'mirejaw_the_ravenous',
    name: 'Mirejaw the Ravenous',
    minLevel: 10,
    maxLevel: 10,
    family: 'mudfin',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 648,
    hpBase: 320,
    hpPerLevel: 58,
    dmgBase: 15,
    dmgPerLevel: 3.7,
    attackSpeed: 1.8,
    armorPerLevel: 26,
    moveSpeed: 8.2,
    aggroRadius: 14,
    aoePulse: { min: 18, max: 26, radius: 10, every: 9, name: 'Ravenous Frenzy', school: 'nature' },
    sapVigor: { chance: 0.3, amount: 25, name: 'Sapping Bite' },
    summonAdds: { mobId: 'mirejaw_frenzy', count: 2, atHpPct: [0.55] },
    loot: [
      { copper: 260, chance: 1 },
      { itemId: 'mudfin_scale', chance: 1 },
      { itemId: 'mirejaw_biteblade', chance: 0.25 },
      { itemId: 'mirejaw_scale_vest', chance: 0.25 },
      { itemId: 'fen_reaver_glaive', chance: 0.25, rollGroup: 'mirejaw_chase' },
      { itemId: 'mirejaw_oracle_staff', chance: 0.25, rollGroup: 'mirejaw_chase' },
      { itemId: 'mirebloom_treads', chance: 0.25 },
    ],
    scale: 1.05,
    color: 0x1abc9c,
  },
  mirejaw_frenzy: {
    id: 'mirejaw_frenzy',
    name: 'Mirejaw Frenzy',
    minLevel: 9,
    maxLevel: 10,
    family: 'mudfin',
    hpBase: 48,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 1.7,
    armorPerLevel: 12,
    moveSpeed: 8.5,
    aggroRadius: 14,
    loot: [],
    scale: 0.75,
    color: 0x1abc9c,
  },
  sloomtooth_the_drowned: {
    id: 'sloomtooth_the_drowned',
    name: 'Sloomtooth the Drowned',
    minLevel: 11,
    maxLevel: 11,
    family: 'mudfin',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 648,
    hpBase: 340,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.8,
    attackSpeed: 1.9,
    armorPerLevel: 28,
    moveSpeed: 8.4,
    aggroRadius: 14,
    // Tidal Sweep: a wide gaff-swing that splashes onto allies near the target.
    cleave: { radius: 8, mult: 0.5, name: 'Tidal Sweep' },
    // Drowning Resurgence: the drowned do not stay dead — one desperate surge of brine
    // heals the tyrant the first time it is brought low.
    desperateHeal: { belowHpPct: 0.3, healPct: 0.25 },
    loot: [
      { copper: 280, chance: 1 },
      { itemId: 'mudfin_scale', chance: 1 },
      { itemId: 'tidereaver_gaff', chance: 0.25, rollGroup: 'sloomtooth_chase' },
      { itemId: 'sloomtooth_tidefang', chance: 0.25, rollGroup: 'sloomtooth_chase' },
      { itemId: 'drowned_tide_scepter', chance: 0.25, rollGroup: 'sloomtooth_chase' },
    ],
    scale: 1.1,
    color: 0x2e86c1,
  },
  mire_widow: {
    id: 'mire_widow',
    name: 'Mirefen Widow',
    minLevel: 8,
    maxLevel: 10,
    family: 'spider',
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 1.8,
    armorPerLevel: 10,
    moveSpeed: 8,
    aggroRadius: 10,
    // Find Weakness: the widow's bite leaves the flesh raw, so critical blows
    // against the victim bite 50% deeper for a few seconds.
    critVuln: { chance: 0.3, critDamage: 0.5, duration: 8, name: 'Exposed Wound' },
    loot: [
      { copper: 38, chance: 1 },
      { itemId: 'widow_venom_sac', chance: 0.65, questId: 'q_widows' },
      { itemId: 'spider_leg', chance: 0.4 },
      { itemId: 'fenbark_leggings', chance: 0.12 },
    ],
    scale: 1.0,
    color: 0x283747,
    componentTags: ['venomSac', 'hide'],
  },
  mirefen_broodmother: {
    id: 'mirefen_broodmother',
    name: 'The Broodmother',
    minLevel: 10,
    maxLevel: 10,
    family: 'spider',
    hpBase: 150,
    hpPerLevel: 26,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 1.8,
    armorPerLevel: 16,
    moveSpeed: 8,
    aggroRadius: 14,
    boss: true,
    stackPoison: {
      chance: 0.35,
      perTick: 3,
      interval: 2,
      duration: 12,
      maxStacks: 5,
      name: 'Brood Venom',
      school: 'nature',
    },
    loot: [
      { copper: 300, chance: 1 },
      { itemId: 'marshstrider_boots', chance: 0.4 },
      { itemId: 'broodmother_silk_robe', chance: 0.25 },
      { itemId: 'spider_leg', chance: 1 },
      { itemId: 'fenwarden_sabatons', chance: 0.3 },
    ],
    scale: 1.4,
    color: 0x641e16,
  },
  drowned_dead: {
    id: 'drowned_dead',
    name: 'Drowned Dead',
    minLevel: 9,
    maxLevel: 11,
    family: 'undead',
    hpBase: 52,
    hpPerLevel: 20,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.3,
    armorPerLevel: 14,
    moveSpeed: 6.5,
    aggroRadius: 11,
    lifeleech: { healFrac: 0.5, chance: 0.35, name: 'Drowning Grasp' },
    // A clammy, fevered touch that rots the living from within, wasting away
    // their constitution (Stamina) and shrinking their health pool.
    plague: { chance: 0.3, vit: 3, duration: 12, name: 'Bog Rot' },
    loot: [
      { copper: 42, chance: 1 },
      { itemId: 'bone_fragments', chance: 0.5 },
      { itemId: 'cracked_fetish', chance: 0.3 },
    ],
    scale: 1.0,
    color: 0x7fb3d5,
  },
  fen_troll: {
    id: 'fen_troll',
    name: 'Mirefen Troll',
    minLevel: 10,
    maxLevel: 12,
    family: 'troll',
    hpBase: 56,
    hpPerLevel: 21,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 11,
    // Withering Rot: the troll's fetid claws rot a struck victim's sinews, draining
    // Agility (thinning their armor and dodge) for a few seconds.
    wither: { chance: 0.3, agi: 5, duration: 8, name: 'Withering Rot', school: 'nature' },
    loot: [
      { copper: 50, chance: 1 },
      { itemId: 'troll_fetish', chance: 0.6, questId: 'q_troll_fetishes' },
      { itemId: 'chipped_tusk', chance: 0.4 },
      { itemId: 'bogiron_nugget', chance: 0.3 },
      { itemId: 'elixir_of_the_bear', chance: 0.07 },
      { itemId: 'marshlight_hauberk', chance: 0.1 },
    ],
    scale: 1.15,
    color: 0x229954,
    componentTags: ['claw', 'tusk'],
  },
  grubjaw: {
    id: 'grubjaw',
    name: 'Grubjaw the Glutton',
    minLevel: 12,
    maxLevel: 12,
    family: 'troll',
    rare: true,
    hpBase: 130,
    hpPerLevel: 26,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 7.5,
    aggroRadius: 13,
    loot: [
      { copper: 200, chance: 1 },
      { itemId: 'grubjaw_tusk', chance: 1, questId: 'q_grubjaw' },
      { itemId: 'chipped_tusk', chance: 1 },
    ],
    purgeOnHit: { chance: 0.3, name: 'Spellgnaw' },
    scale: 1.3,
    color: 0x145a32,
  },
  gravecaller_cultist: {
    id: 'gravecaller_cultist',
    name: 'Gravecaller Cultist',
    minLevel: 10,
    maxLevel: 12,
    family: 'humanoid',
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    // The cultist's hex leaves the victim taking more damage from everyone —
    // a soft-up that rewards a group focusing the cursed player's target down.
    vulnerability: {
      chance: 0.2,
      amp: 0.15,
      duration: 10,
      name: 'Curse of Frailty',
      school: 'shadow',
    },
    loot: [
      { copper: 55, chance: 1 },
      { itemId: 'linen_scrap', chance: 0.3 },
      { itemId: 'tallow_candle', chance: 0.3 },
    ],
    // The cultist's muttered curse weakens its prey: a hexed victim deals less
    // damage and heals for less until the hex fades.
    hex: { chance: 0.3, reductionPct: 0.2, duration: 10, name: 'Weakening Hex', school: 'shadow' },
    scale: 1.0,
    color: 0x6c3483,
    componentTags: ['cloth'],
  },
  gravecaller_summoner: {
    id: 'gravecaller_summoner',
    name: 'Gravecaller Summoner',
    minLevel: 11,
    maxLevel: 12,
    family: 'humanoid',
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 12,
    silence: { chance: 0.3, duration: 4, name: 'Silencing Shriek', school: 'shadow' },
    // Grave Blight: a landed hit can sear undeath into the wound, devouring the
    // next 120 healing the victim receives before it fades. A sustain-denial axis
    // that complements (not compounds) the summoner's silence lockout: healers
    // must out-pace the blight or top off after it lapses.
    healAbsorb: { chance: 0.25, amount: 120, duration: 10, name: 'Grave Blight', school: 'shadow' },
    loot: [
      { copper: 60, chance: 1 },
      { itemId: 'cult_cipher', chance: 0.6, questId: 'q_summoners' },
    ],
    scale: 1.0,
    color: 0x884ea0,
    componentTags: ['cloth'],
  },
  gravecaller_mender: {
    id: 'gravecaller_mender',
    name: 'Gravecaller Mender',
    minLevel: 11,
    maxLevel: 12,
    family: 'humanoid',
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 12,
    // Grave Mending: keeps its cultist pack alive, knitting every wounded ally's
    // wounds shut on a slow cadence. Pull it away from the camp — or drop it
    // first — or the fight never ends.
    mendAlly: {
      healMin: 26,
      healMax: 38,
      radius: 14,
      every: 6,
      name: 'Grave Mending',
      school: 'shadow',
    },
    // Draining Litany: the mender siphons the victim's vigour to fuel its grave
    // prayers, inflating every ability the victim uses by 40% for 8s on a hit.
    costTax: { chance: 0.3, pct: 0.4, duration: 8, name: 'Draining Litany', school: 'shadow' },
    loot: [
      { copper: 58, chance: 1 },
      { itemId: 'cult_cipher', chance: 0.4, questId: 'q_summoners' },
      { itemId: 'tallow_candle', chance: 0.3 },
      { itemId: 'duskthorn_mantle', chance: 0.12 },
    ],
    scale: 1.0,
    color: 0x9b59b6,
  },
  sister_nhalia: {
    id: 'sister_nhalia',
    name: 'Sister Nhalia',
    minLevel: 12,
    maxLevel: 12,
    family: 'humanoid',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 648,
    hpBase: 330,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.8,
    attackSpeed: 2.0,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    aoePulse: { min: 18, max: 26, radius: 11, every: 9, name: 'Dirge of Nhalia', school: 'shadow' },
    // Spirit Siphon: the priestess's touch drains a caster's Spirit, choking
    // their out-of-combat mana regen for the duration (see siphonSpirit affix).
    siphonSpirit: { chance: 0.3, int: 5, duration: 10, name: 'Spirit Siphon', school: 'shadow' },
    // A bone-chilling shriek that sends the living fleeing in terror — her dirge
    // is grief, her wail is dread. Telegraphed: first scream after one interval.
    terrify: { radius: 12, every: 16, duration: 3, name: 'Keening Wail', school: 'shadow' },
    summonAdds: { mobId: 'nhalia_mourner', count: 2, atHpPct: [0.65, 0.35] },
    loot: [
      { copper: 350, chance: 1 },
      { itemId: 'tallow_candle', chance: 1 },
      { itemId: 'nhalias_funeral_wraps', chance: 0.25 },
      { itemId: 'nhalias_dirgeblade', chance: 0.25, rollGroup: 'sister_nhalia_chase' },
    ],
    scale: 1.08,
    color: 0x3b1f4a,
  },
  nhalia_mourner: {
    id: 'nhalia_mourner',
    name: 'Nhalia Mourner',
    minLevel: 11,
    maxLevel: 12,
    family: 'humanoid',
    hpBase: 46,
    hpPerLevel: 17,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    // Curse of Tongues: the mourners' dirge garbles a caster's incantations, slowing
    // their spell cast times by 30% for 10s on a landed hit (30% chance).
    tongues: { chance: 0.3, mult: 1.3, duration: 10, name: 'Dirge of Tongues', school: 'shadow' },
    loot: [],
    scale: 0.95,
    color: 0x332044,
  },
  deacon_voss: {
    id: 'deacon_voss',
    name: 'Deacon Voss',
    minLevel: 12,
    maxLevel: 12,
    family: 'humanoid',
    hpBase: 200,
    hpPerLevel: 30,
    dmgBase: 11,
    dmgPerLevel: 2.5,
    attackSpeed: 2.4,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 14,
    boss: true,
    aoePulse: { min: 10, max: 14, radius: 10, every: 12, name: 'Drowning Hymn' },
    // The deacon brands the faithless with a searing arcane rune that festers.
    arcaneRot: {
      chance: 0.3,
      perTick: 7,
      interval: 3,
      duration: 12,
      name: 'Profane Rune',
      school: 'arcane',
    },
    loot: [
      { copper: 600, chance: 1 },
      { itemId: 'tallow_candle', chance: 1 },
      { itemId: 'voss_sanctified_mace', chance: 0.25 },
      { itemId: 'fenshadow_maul', chance: 0.25 },
    ],
    scale: 1.3,
    color: 0x512e5f,
  },
  bog_bloat: {
    id: 'bog_bloat',
    name: 'Bog Bloat',
    minLevel: 9,
    maxLevel: 11,
    family: 'beast',
    hpBase: 44,
    hpPerLevel: 17,
    dmgBase: 7,
    dmgPerLevel: 2.0,
    attackSpeed: 2.6,
    armorPerLevel: 9,
    moveSpeed: 6,
    aggroRadius: 10,
    // A swollen marsh gas-bag: when slain its corpse swells for 1.5s, then
    // bursts in a cloud of caustic spores — get clear or share the blast.
    deathThroes: {
      min: 14,
      max: 22,
      radius: 8,
      delay: 1.5,
      name: 'Caustic Spores',
      school: 'nature',
    },
    loot: [
      { copper: 40, chance: 1 },
      { itemId: 'tangled_weed', chance: 0.5 },
    ],
    scale: 1.1,
    color: 0x6b8e23,
  },
};

// ---------------------------------------------------------------------------
// NPCs (Fenbridge hub)
// ---------------------------------------------------------------------------
