// Zone 1, Eastbrook Vale (levels 1-7). The starter zone: town of Eastbrook,
// wolves and boars, the bandit camp, and Brother Aldric's Gravecaller chain
// leading to the Hollow Crypt.

import { EASTBROOK_GRAND_ARMOURY } from '../../building_layout';
import { EASTBROOK_LAYOUT, EASTBROOK_NPC_PLACEMENTS_BY_ID } from '../../eastbrook_layout';
import { WORK_ORDER_CADENCE_TICKS } from '../../professions/cadence';
import type {
  CampDef,
  GroundObjectDef,
  MobTemplate,
  NpcDef,
  QuestDef,
  ZoneDef,
  ZonePropsDef,
} from '../../types';

export const ZONE1_MOBS: Record<string, MobTemplate> = {
  warlock_imp: {
    id: 'warlock_imp',
    name: 'Fire Demon',
    minLevel: 1,
    maxLevel: 20,
    family: 'demon',
    race: 'demon',
    element: 'fire',
    elementLevel: 1,
    size: 'small',
    // Kukre, level 11 in the reference table.
    hp: 507,
    atk: 28,
    atk2: 37,
    def: 15,
    mdef: 0,
    baseExp: 38,
    jobExp: 28,
    str: 0,
    agi: 11,
    vit: 11,
    int: 5,
    dex: 16,
    luk: 2,
    attackRange: 1,
    hpBase: 24,
    hpPerLevel: 11,
    dmgBase: 2,
    dmgPerLevel: 0.7,
    attackSpeed: 2.0,
    armorPerLevel: 5,
    moveSpeed: 8,
    aggroRadius: 0,
    loot: [{ itemId: 'card_warlock_imp', chance: 0.03 }],
    scale: 0.65,
    color: 0xff5a2e,
    petRole: 'ranged_dps',
    petSpell: { name: 'Ashbolt', school: 'fire', min: 8, max: 11, range: 24, every: 2.0 },
  },
  warlock_voidwalker: {
    id: 'warlock_voidwalker',
    name: 'Void Demon',
    minLevel: 10,
    maxLevel: 20,
    family: 'demon',
    race: 'demon',
    element: 'shadow',
    elementLevel: 1,
    size: 'medium',
    // Zombie, level 15 in the reference table.
    hp: 534,
    atk: 67,
    atk2: 79,
    def: 0,
    mdef: 10,
    baseExp: 50,
    jobExp: 33,
    str: 0,
    agi: 8,
    vit: 7,
    int: 0,
    dex: 15,
    luk: 0,
    attackRange: 1,
    hpBase: 95,
    hpPerLevel: 24,
    dmgBase: 3,
    dmgPerLevel: 1.0,
    attackSpeed: 2.4,
    armorPerLevel: 28,
    moveSpeed: 7.2,
    aggroRadius: 0,
    loot: [],
    scale: 0.9,
    color: 0x6b4bb5,
    petRole: 'melee_tank',
  },
  forest_wolf: {
    id: 'forest_wolf',
    name: 'Forest Wolf',
    minLevel: 1,
    maxLevel: 2,
    family: 'beast',
    race: 'brute',
    element: 'neutral',
    elementLevel: 1,
    size: 'medium',
    // Lunatic, level 3 in the reference table.
    hp: 60,
    atk: 9,
    atk2: 12,
    def: 0,
    mdef: 20,
    baseExp: 6,
    jobExp: 2,
    str: 0,
    agi: 3,
    vit: 3,
    int: 10,
    dex: 8,
    luk: 60,
    attackRange: 1,
    hpBase: 40,
    hpPerLevel: 14,
    dmgBase: 3,
    dmgPerLevel: 1.6,
    attackSpeed: 2.0,
    armorPerLevel: 10,
    moveSpeed: 8,
    aggroRadius: 10,
    loot: [
      { itemId: 'card_forest_wolf', chance: 0.03 },
      { copper: 8, chance: 1 },
      { itemId: 'wolf_fang', chance: 0.45 },
      { itemId: 'milepost_boots', chance: 0.1 },
      { itemId: 'wolfhide_satchel', chance: 0.02 },
    ],
    scale: 0.9,
    color: 0x7f8c8d,
    packFrenzy: { radius: 12, hasteMult: 1.3, duration: 8 },
    componentTags: ['hide', 'fang'],
  },
  old_greyjaw: {
    id: 'old_greyjaw',
    name: 'Old Greyjaw',
    minLevel: 4,
    maxLevel: 4,
    family: 'beast',
    race: 'brute',
    element: 'neutral',
    elementLevel: 1,
    size: 'medium',
    // Picky, level 4 in the reference table.
    hp: 83,
    atk: 8,
    atk2: 11,
    def: 20,
    mdef: 0,
    baseExp: 5,
    jobExp: 4,
    str: 0,
    agi: 3,
    vit: 3,
    int: 10,
    dex: 11,
    luk: 20,
    attackRange: 1,
    rare: true,
    hpBase: 110,
    hpPerLevel: 20,
    dmgBase: 5,
    dmgPerLevel: 2.0,
    attackSpeed: 1.8,
    armorPerLevel: 16,
    moveSpeed: 8.5,
    aggroRadius: 12,
    // The old wolf turns savage as the fight wears on: each wound it takes can
    // send it into a blood frenzy, swinging 30% faster for 8s.
    frenzyOnHit: { chance: 0.25, hasteMult: 1.3, duration: 8, name: 'Blood Frenzy' },
    loot: [
      { copper: 60, chance: 1 },
      { itemId: 'greyjaw_fang', chance: 1, questId: 'q_greyjaw' },
      { itemId: 'wolf_fang', chance: 1 },
      { itemId: 'wolfhide_satchel', chance: 0.35 },
      { itemId: 'acolyte_chain_grips', chance: 0.25 },
    ],
    scale: 1.25,
    color: 0x566061,
    componentTags: ['hide', 'fang', 'claw'],
  },
  wild_boar: {
    id: 'wild_boar',
    name: 'Wild Boar',
    minLevel: 2,
    maxLevel: 3,
    family: 'beast',
    race: 'brute',
    element: 'earth',
    elementLevel: 1,
    size: 'medium',
    // Picky, level 3 in the reference table.
    hp: 80,
    atk: 9,
    atk2: 12,
    def: 0,
    mdef: 0,
    baseExp: 4,
    jobExp: 3,
    str: 0,
    agi: 3,
    vit: 3,
    int: 5,
    dex: 10,
    luk: 30,
    attackRange: 1,
    hpBase: 38,
    hpPerLevel: 16,
    dmgBase: 4,
    dmgPerLevel: 1.8,
    attackSpeed: 2.2,
    armorPerLevel: 14,
    moveSpeed: 7.5,
    aggroRadius: 9,
    // Stiff bristles prick anyone who melees the boar.
    thorns: { value: 2, name: 'Bristled Hide' },
    loot: [
      { itemId: 'card_wild_boar', chance: 0.03 },
      { copper: 12, chance: 1 },
      { itemId: 'boar_hide', chance: 0.6, questId: 'q_boars' },
      { itemId: 'tough_jerky', chance: 0.3 },
      { itemId: 'trail_leggings', chance: 0.1 },
    ],
    scale: 0.85,
    color: 0x935116,
    componentTags: ['hide', 'tusk', 'meat'],
  },
  webwood_spider: {
    id: 'webwood_spider',
    name: 'Sableweb Lurker',
    minLevel: 2,
    maxLevel: 4,
    family: 'spider',
    race: 'insect',
    element: 'poison',
    elementLevel: 1,
    size: 'small',
    // Fabre, level 2 in the reference table.
    hp: 63,
    atk: 8,
    atk2: 11,
    def: 0,
    mdef: 0,
    baseExp: 3,
    jobExp: 2,
    str: 0,
    agi: 2,
    vit: 4,
    int: 0,
    dex: 7,
    luk: 5,
    attackRange: 1,
    hpBase: 36,
    hpPerLevel: 15,
    dmgBase: 4,
    dmgPerLevel: 1.7,
    attackSpeed: 1.8,
    armorPerLevel: 8,
    moveSpeed: 8,
    aggroRadius: 10,
    venom: {
      chance: 0.35,
      perTick: 2,
      interval: 2,
      duration: 10,
      name: 'Spider Venom',
      school: 'nature',
    },
    ensnare: { chance: 0.25, duration: 3, name: 'Sticky Web', school: 'nature' },
    loot: [
      { itemId: 'card_webwood_spider', chance: 0.03 },
      { copper: 14, chance: 1 },
      { itemId: 'webwood_silk', chance: 0.55, questId: 'q_spiders' },
      { itemId: 'spider_leg', chance: 0.4 },
      { itemId: 'mosshide_vest', chance: 0.12 },
    ],
    scale: 0.9,
    color: 0x4a235a,
    componentTags: ['venomSac', 'silk'],
  },
  mogger: {
    id: 'mogger',
    name: 'Mogger',
    minLevel: 6,
    maxLevel: 6,
    family: 'humanoid',
    race: 'demihuman',
    element: 'neutral',
    elementLevel: 2,
    size: 'medium',
    // Thief, level 6 in the reference table.
    def: 5,
    mdef: 0,
    baseExp: 17,
    jobExp: 5,
    str: 0,
    agi: 6,
    vit: 6,
    int: 0,
    dex: 11,
    luk: 0,
    attackRange: 1,
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 4,
    hpBase: 300,
    hpPerLevel: 58,
    dmgBase: 12,
    dmgPerLevel: 3.5,
    attackSpeed: 2.2,
    armorPerLevel: 34,
    moveSpeed: 7.4,
    aggroRadius: 14,
    aoePulse: { min: 14, max: 20, radius: 8, every: 10, name: 'Ground Pound', school: 'physical' },
    summonAdds: { mobId: 'mogger_lackey', count: 2, atHpPct: [0.7] },
    enrage: { belowHpPct: 0.3, dmgMult: 1.6, hasteMult: 1.3 },
    wardAllies: {
      radius: 12,
      every: 12,
      amount: 70,
      duration: 8,
      name: 'Bracing Order',
      school: 'physical',
    },
    loot: [
      { itemId: 'card_mogger', chance: 0.12 },
      { copper: 180, chance: 1 },
      { itemId: 'linen_scrap', chance: 1 },
      { itemId: 'moggers_stomper_boots', chance: 0.3 },
      { itemId: 'moggers_shiv', chance: 0.25, rollGroup: 'mogger_chase' },
      { itemId: 'cryptstalker_jerkin', chance: 0.25, rollGroup: 'mogger_chase' },
      { itemId: 'valefire_lantern', chance: 0.2 },
    ],
    scale: 1.28,
    color: 0x8e5b33,
  },
  mogger_lackey: {
    id: 'mogger_lackey',
    name: 'Mogger Lackey',
    minLevel: 5,
    maxLevel: 6,
    family: 'humanoid',
    race: 'demihuman',
    element: 'neutral',
    elementLevel: 1,
    size: 'medium',
    // Thief, level 6 in the reference table.
    def: 5,
    mdef: 0,
    baseExp: 17,
    jobExp: 5,
    str: 0,
    agi: 6,
    vit: 6,
    int: 0,
    dex: 11,
    luk: 0,
    attackRange: 1,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 6,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 12,
    stunOnHit: { chance: 0.12, duration: 1, name: 'Skullthump', school: 'physical' },
    loot: [],
    scale: 0.95,
    color: 0x7b4b2b,
  },
  mudfin_murloc: {
    id: 'mudfin_murloc',
    name: 'Mudfin Skulker',
    minLevel: 3,
    maxLevel: 5,
    family: 'mudfin',
    race: 'fish',
    element: 'water',
    elementLevel: 1,
    size: 'medium',
    // Roda, level 5 in the reference table.
    hp: 133,
    atk: 11,
    atk2: 14,
    def: 0,
    mdef: 5,
    baseExp: 6,
    jobExp: 5,
    str: 0,
    agi: 5,
    vit: 5,
    int: 5,
    dex: 10,
    luk: 5,
    attackRange: 1,
    hpBase: 36,
    hpPerLevel: 17,
    dmgBase: 5,
    dmgPerLevel: 1.9,
    attackSpeed: 1.9,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 13, // murlocs aggro from far and bring friends
    loot: [
      { itemId: 'card_mudfin_murloc', chance: 0.03 },
      { copper: 18, chance: 1 },
      { itemId: 'mudfin_scale', chance: 0.5 },
      { itemId: 'linen_scrap', chance: 0.2 },
    ],
    scale: 0.8,
    color: 0x52be80,
    componentTags: ['gills', 'hide'],
    // Mudfin Hex: the skulker's oracle-chant briefly turns a foe into a critter.
    // Low chance and it breaks the instant the victim takes damage (the murloc's
    // own next bite ends it), so it's a brief flavor incap, but a murloc pack
    // can chain it just long enough to make a careless pull dangerous.
    polymorphHex: { chance: 0.12, duration: 4, name: 'Mudfin Hex', school: 'nature' },
  },
  tunnel_rat: {
    id: 'tunnel_rat',
    name: 'Deeprock Digger',
    minLevel: 4,
    maxLevel: 6,
    family: 'burrower',
    race: 'brute',
    element: 'earth',
    elementLevel: 1,
    size: 'small',
    // Condor, level 5 in the reference table.
    def: 0,
    mdef: 0,
    baseExp: 6,
    jobExp: 5,
    str: 0,
    agi: 13,
    vit: 5,
    int: 0,
    dex: 13,
    luk: 10,
    attackRange: 1,
    hpBase: 42,
    hpPerLevel: 18,
    dmgBase: 6,
    dmgPerLevel: 2.0,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 10,
    loot: [
      { itemId: 'card_tunnel_rat', chance: 0.03 },
      { copper: 22, chance: 1 },
      { itemId: 'tallow_candle', chance: 0.6 },
      { itemId: 'blessed_wax', chance: 0.45, questId: 'q_rite' },
      { itemId: 'linen_scrap', chance: 0.25 },
      { itemId: 'mossy_handwraps', chance: 0.15 },
      { itemId: 'thornling_grips', chance: 0.15 },
    ],
    scale: 0.85,
    color: 0x9c640c,
  },
  grix_the_tunnelking: {
    id: 'grix_the_tunnelking',
    name: 'Grix the Tunnelking',
    minLevel: 7,
    maxLevel: 7,
    family: 'burrower',
    race: 'brute',
    element: 'earth',
    elementLevel: 2,
    size: 'medium',
    // Savage, level 7 in the reference table.
    def: 0,
    mdef: 0,
    baseExp: 14,
    jobExp: 12,
    str: 0,
    agi: 7,
    vit: 14,
    int: 5,
    dex: 12,
    luk: 35,
    attackRange: 1,
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 432,
    hpBase: 280,
    hpPerLevel: 52,
    dmgBase: 11,
    dmgPerLevel: 3.3,
    attackSpeed: 2.0,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 13,
    aoePulse: { min: 12, max: 18, radius: 8, every: 9, name: 'Cave-In', school: 'physical' },
    summonAdds: { mobId: 'tunnel_rat', count: 2, atHpPct: [0.55, 0.3] },
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.3 },
    loot: [
      { copper: 150, chance: 1 },
      { itemId: 'tallow_candle', chance: 1 },
      // The hoarder's stash, a guaranteed step up the potion ladder this early.
      { itemId: 'lesser_healing_potion', chance: 1 },
      { itemId: 'tunnelkings_spade', chance: 0.3 },
      { itemId: 'moggers_copper_cudgel', chance: 0.25, rollGroup: 'grix_tunnelking_chase' },
      { itemId: 'hollowbone_hauberk', chance: 0.25, rollGroup: 'grix_tunnelking_chase' },
      { itemId: 'briarroot_staff', chance: 0.3 },
    ],
    scale: 1.15,
    color: 0xb9770e,
  },
  vale_bandit: {
    id: 'vale_bandit',
    name: 'Vale Bandit',
    minLevel: 3,
    maxLevel: 5,
    family: 'humanoid',
    race: 'demihuman',
    element: 'neutral',
    elementLevel: 1,
    size: 'medium',
    // Ant, level 4 in the reference table.
    hp: 420,
    atk: 1,
    atk2: 2,
    def: 20,
    mdef: 20,
    baseExp: 5,
    jobExp: 4,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 20,
    attackRange: 1,
    hpBase: 40,
    hpPerLevel: 18,
    dmgBase: 5,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    loot: [
      { itemId: 'card_vale_bandit', chance: 0.03 },
      { copper: 25, chance: 1 },
      { itemId: 'bandit_bandana', chance: 0.5 },
      { itemId: 'linen_scrap', chance: 0.3 },
    ],
    scale: 1.0,
    color: 0x943126,
    // A practiced thug flings a handful of road grit to foul your aim.
    blind: { chance: 0.25, miss: 0.3, duration: 5, name: 'Blinding Powder', school: 'physical' },
    componentTags: ['cloth'],
  },
  restless_bones: {
    id: 'restless_bones',
    name: 'Restless Bones',
    minLevel: 5,
    maxLevel: 7,
    family: 'undead',
    race: 'undead',
    element: 'undead',
    elementLevel: 1,
    size: 'medium',
    // Thief, level 6 in the reference table.
    def: 5,
    mdef: 0,
    baseExp: 17,
    jobExp: 5,
    str: 0,
    agi: 6,
    vit: 6,
    int: 0,
    dex: 11,
    luk: 0,
    attackRange: 1,
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.1,
    attackSpeed: 2.3,
    armorPerLevel: 14,
    moveSpeed: 6.5,
    aggroRadius: 11,
    loot: [
      { itemId: 'card_restless_bones', chance: 0.03 },
      { copper: 30, chance: 1 },
      { itemId: 'bone_fragments', chance: 0.6 },
      { itemId: 'ghostly_essence', chance: 0.55, questId: 'q_rite' },
    ],
    scale: 1.0,
    color: 0xd5dbdb,
    // A grave-cold wail saps the strength from the living it strikes.
    demoralize: { ap: 4, duration: 8, name: 'Withering Wail' },
    // Grave-touch: a clawing swing may fester a creeping necrotic rot (shadow DoT).
    soulrot: { chance: 0.25, perTick: 4, interval: 3, duration: 12, name: 'Soulrot' },
  },
  captain_verlan: {
    // A rare named undead champion risen among the ruins' Restless Bones,
    // the undead family's rare elite, filling the gap beside Old Greyjaw
    // (beast), Elder Bristleback (beast), Sableweb Matriarch (spider) and
    // Mogger (humanoid). A heavy, slow striker that erupts in a shadow nova
    // and goes berserk when low; loot mirrors the other rare elites.
    id: 'captain_verlan',
    name: 'Captain Verlan',
    minLevel: 7,
    maxLevel: 7,
    family: 'undead',
    race: 'undead',
    element: 'undead',
    elementLevel: 2,
    size: 'medium',
    // Skeleton, level 10 in the reference table.
    def: 10,
    mdef: 10,
    baseExp: 18,
    jobExp: 14,
    str: 0,
    agi: 5,
    vit: 10,
    int: 0,
    dex: 12,
    luk: 0,
    attackRange: 1,
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 7.2,
    hpBase: 280,
    hpPerLevel: 56,
    dmgBase: 12,
    dmgPerLevel: 3.4,
    attackSpeed: 2.6,
    armorPerLevel: 32,
    moveSpeed: 7.4,
    aggroRadius: 13,
    aoePulse: {
      min: 13,
      max: 19,
      radius: 9,
      every: 9,
      name: 'Hollow Nova',
      school: 'shadow',
      fx: 'nova',
    },
    enrage: { belowHpPct: 0.3, dmgMult: 1.5, hasteMult: 1.3 },
    loot: [
      { copper: 160, chance: 1 },
      { itemId: 'bone_fragments', chance: 1 },
      { itemId: 'oathbound_greaves', chance: 0.3 },
      { itemId: 'verlans_oathblade', chance: 0.25, rollGroup: 'verlan_chase' },
      { itemId: 'hollow_vigil_staff', chance: 0.25, rollGroup: 'verlan_chase' },
      { itemId: 'gravewardens_shiv', chance: 0.25, rollGroup: 'verlan_chase' },
    ],
    scale: 1.26,
    color: 0x3b4a5a,
  },
  wraithbinder_maldrec: {
    id: 'wraithbinder_maldrec',
    name: 'Wraithbinder Maldrec',
    minLevel: 7,
    maxLevel: 7,
    family: 'undead',
    race: 'undead',
    element: 'undead',
    elementLevel: 2,
    size: 'medium',
    // Skeleton, level 10 in the reference table.
    def: 10,
    mdef: 10,
    baseExp: 18,
    jobExp: 14,
    str: 0,
    agi: 5,
    vit: 10,
    int: 0,
    dex: 12,
    luk: 0,
    attackRange: 1,
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 432,
    hpBase: 320,
    hpPerLevel: 60,
    dmgBase: 12,
    dmgPerLevel: 3.4,
    attackSpeed: 2.3,
    armorPerLevel: 28,
    moveSpeed: 6.8,
    aggroRadius: 13,
    // A fallen Gravecaller who bound his own soul to the chapel dead. A pulse of
    // grave-cold shadow rolls off him, and he tears the restless bones from the
    // ground to fight at his side, growing frantic as he is unmade.
    aoePulse: { min: 13, max: 19, radius: 9, every: 9, name: 'Grave Chill', school: 'shadow' },
    summonAdds: { mobId: 'restless_bones', count: 2, atHpPct: [0.65, 0.35] },
    enrage: { belowHpPct: 0.3, dmgMult: 1.5, hasteMult: 1.3 },
    loot: [
      { copper: 160, chance: 1 },
      { itemId: 'bone_fragments', chance: 1 },
      { itemId: 'maldrecs_soulbinder', chance: 0.25 },
      { itemId: 'hollowbone_hauberk', chance: 0.25, rollGroup: 'maldrec_chase' },
      { itemId: 'gravewoven_raiment', chance: 0.25, rollGroup: 'maldrec_chase' },
      { itemId: 'cryptstalker_jerkin', chance: 0.25, rollGroup: 'maldrec_chase' },
    ],
    scale: 1.22,
    color: 0x6f7f8f,
  },
  gorrak: {
    id: 'gorrak',
    name: 'Gorrak the Ruthless',
    minLevel: 6,
    maxLevel: 6,
    family: 'humanoid',
    race: 'demihuman',
    element: 'neutral',
    elementLevel: 3,
    size: 'medium',
    // Nightmare, level 30 in the reference table.
    hp: 2000,
    atk: 100,
    atk2: 200,
    def: 0,
    mdef: 40,
    baseExp: 512,
    jobExp: 387,
    str: 0,
    agi: 100,
    vit: 0,
    int: 0,
    dex: 100,
    luk: 0,
    attackRange: 1,
    hpBase: 160,
    hpPerLevel: 30,
    dmgBase: 8,
    dmgPerLevel: 2.4,
    attackSpeed: 2.4,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    boss: true,
    loot: [
      { copper: 250, chance: 1 },
      { itemId: 'bandit_bandana', chance: 1 },
      { itemId: 'oiled_boots', chance: 0.5 },
      { itemId: 'quilted_trousers', chance: 0.5 },
      { itemId: 'gorraks_cruel_chopper', chance: 0.25 },
      { itemId: 'gorraks_cleaver', chance: 0.3 },
      { itemId: 'votive_chain_belt', chance: 0.3 },
    ],
    scale: 1.25,
    color: 0x6c3483,
  },
};

// ---------------------------------------------------------------------------
// NPCs
// ---------------------------------------------------------------------------
