// GENERATED by scripts/spiritvale/build_skills.mjs. Do not edit by hand.
// Source: docs/design/data/spiritvale-raw/. Regenerate with `npm run skills:content`;
// tests/spiritvale_skills.test.ts fails if the committed output has drifted.
//
// The 4 pets the Summoner tree calls.

import type { SummonDef } from './types';

export const SPIRITVALE_SUMMONS: Readonly<Record<string, SummonDef>> = {
  'Angel Mage': {
    id: 'Angel Mage',
    name: 'Angel Mage',
    hostile: false,
    stats: [{ stat: 'Str', base: 5, per: 0.2 }, { stat: 'Agi', base: 5, per: 0.2 }, { stat: 'Vit', base: 10, per: 0.4 }, { stat: 'Int', base: 15, per: 0.6 }, { stat: 'Dex', base: 10, per: 0.4 }, { stat: 'Luk', base: 5, per: 0.2 }],
    skills: [
      { id: 'Heal', level: 5, chance: 1, castTime: 0, cooldown: 1, castType: 'unit' },
      { id: 'HolyLight', level: 5, chance: 1, castTime: 1, cooldown: 0, castType: 'unit' },
      { id: 'AngelicBlessing', level: 5, chance: 1, castTime: 0, cooldown: 5, targetStatus: 'AngelicBlessing', castType: 'toggle' },
      { id: 'Smite', level: 5, chance: 1, castTime: 0, cooldown: 3, castType: 'unit' },
      { id: 'FieldHealing', level: 5, chance: 1, castTime: 0.5, cooldown: 5, castType: 'ground' },
    ],
  },
  'Cactus Boss': {
    id: 'Cactus Boss',
    name: 'Cactus Boss',
    hostile: false,
    stats: [{ stat: 'Str', base: 15, per: 0.6 }, { stat: 'Agi', base: 5, per: 0.2 }, { stat: 'Vit', base: 15, per: 0.6 }, { stat: 'Int', base: 5, per: 0.2 }, { stat: 'Dex', base: 5, per: 0.2 }, { stat: 'Luk', base: 5, per: 0.2 }],
    skills: [
      { id: 'Taunt', level: 5, chance: 1, castTime: 0, cooldown: 5, castType: 'none' },
      { id: 'SpearStab', level: 5, chance: 1, castTime: 0, cooldown: 3, castType: 'unit' },
      { id: 'Armored', level: 5, chance: 1, castTime: 0, cooldown: 5, targetStatus: 'Armored', castType: 'toggle' },
      { id: 'Stomp', level: 5, chance: 1, castTime: 0, cooldown: 4, castType: 'ground' },
      { id: 'ShieldBash', level: 5, chance: 1, castTime: 0, cooldown: 3, castType: 'ground' },
    ],
  },
  'Cat Bolt': {
    id: 'Cat Bolt',
    name: 'Cat Bolt',
    hostile: false,
    stats: [{ stat: 'Str', base: 5, per: 0.2 }, { stat: 'Agi', base: 15, per: 0.6 }, { stat: 'Vit', base: 5, per: 0.2 }, { stat: 'Int', base: 15, per: 0.6 }, { stat: 'Dex', base: 5, per: 0.2 }, { stat: 'Luk', base: 5, per: 0.2 }],
    skills: [
      { id: 'Thunderbolt', level: 5, chance: 1, castTime: 4, cooldown: 1, castType: 'unit' },
      { id: 'LightningStrike', level: 5, chance: 1, castTime: 0, cooldown: 3, castType: 'ground' },
      { id: 'LightningCoat', level: 5, chance: 1, castTime: 0, cooldown: 5, targetStatus: 'LightningCoat', castType: 'toggle' },
      { id: 'ThunderStorm', level: 5, chance: 1, castTime: 5, cooldown: 1, castType: 'ground' },
      { id: 'LightningRelease', level: 5, chance: 1, castTime: 1, cooldown: 1, castType: 'ground' },
    ],
  },
  'Werewolf': {
    id: 'Werewolf',
    name: 'Werewolf',
    hostile: false,
    stats: [{ stat: 'Str', base: 15, per: 0.6 }, { stat: 'Agi', base: 5, per: 0.2 }, { stat: 'Vit', base: 10, per: 0.4 }, { stat: 'Int', base: 5, per: 0.2 }, { stat: 'Dex', base: 5, per: 0.2 }, { stat: 'Luk', base: 10, per: 0.4 }],
    skills: [
      { id: 'Bash', level: 5, chance: 1, castTime: 0, cooldown: 0, castType: 'unit' },
      { id: 'AxeVortex', level: 5, chance: 1, castTime: 0, cooldown: 5, castType: 'none' },
      { id: 'BloodLust', level: 5, chance: 1, castTime: 0, cooldown: 5, targetStatus: 'BloodLust', castType: 'toggle' },
      { id: 'TwohandQuicken', level: 5, chance: 1, castTime: 0, cooldown: 5, targetStatus: 'TwohandQuicken', castType: 'none' },
      { id: 'ShadowRelease', level: 5, chance: 1, castTime: 0.5, cooldown: 1, castType: 'unit' },
    ],
  },
};
